### ISSUE TITLE
Point size does not persist

### ISSUE THREAD

**Issue by gianpaolop** [microsoft/SandDance#106]
The visual, in Power BI, seams not to remember Point Size (as set in a previous session)

**Comment by danmarshall** [comment]
Hello @gianpaolop - you need to be in Edit mode, then Save for the changes to be saved. Modifications while viewing (not editing) are not saved, as in all Power BI visuals.

**Comment by danmarshall** [comment]
I believe this is fixed. If not, please re-open this issue, thanks!
