### ISSUE TITLE
Any plans to load data from remote sources?

### ISSUE THREAD

**Issue by vogt4nick** [microsoft/SandDance#116]
The usage appears limited to

> Right-click on a .csv or .tsv file and choose View in SandDance.

I work primarily with databases, and I'm sure I'm not alone. It takes time to query data from a database and save the data in local files. It'd be useful if SandDance did this work for me. 

Are there any plans to address this use case? 

Are there any alternatives you can suggest? Maybe this can be accomplished with another, existing VS Code extension and I just don't know where to look?

**Comment by danmarshall** [comment]
[Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is) is designed to accomplish this 🤓 and we have a [SandDance extension](https://docs.microsoft.com/en-us/sql/azure-data-studio/sanddance-extension) for it.

**Comment by danmarshall** [comment]
Also, you can enter a URL in the UI at https://sanddance.js.org/app/

Click the "Sample Data" button to drop-down other data file choices, then choose URL.
![image](https://user-images.githubusercontent.com/11507384/66964475-9aa0cc00-f02b-11e9-8e55-5404768e78fc.png)

FYI The other server will need to accept [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
