### ISSUE TITLE
sanddance-react - Not found 

### ISSUE THREAD

**Issue by a5l3** [microsoft/SandDance#117]
Heya,

Tried installing sunddance-react, this issue should bug you to publish it before the name is taken by a troll :)

``` Dart
➜  sd git:(master) code .
➜  sd git:(master) npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/sanddance-react - Not found
npm ERR! 404
npm ERR! 404  'sanddance-react@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

On another topic, it would be great to see the new WebGPU api implemented for Sanddance once its finalized.

**Comment by Icemap** [comment]
"sanddance-react" -> "@msrvida/sanddance-react"

**Comment by danmarshall** [comment]
Hi @a5l3 , thanks for the comments. As @Icemap points out, publishing of SandDance components is under the @msrvida org name. Also I'll keep a tab on WebGPU 👍

**Comment by a5l3** [comment]
Heya @danmarshall, 
Found this, https://dawn.googlesource.com/dawn/, could be useful, exposes a 1 to 1 c/c++ api. 
N-API is pretty rough, but can be useful for web projects wanting to use SandDance in the future. I know a few have used c++ in Electron, maybe thats another route for the VSCode extension. 
Excited to see the VSCode tooling evolve. 
Thats all from me.
