### ISSUE TITLE
How to use data  form a database?

### ISSUE THREAD

**Issue by win32nipuh** [microsoft/SandDance#122]
How to use data from a database instead of reading it from a file like here:

```
 vega.loader().load('../../sample-data/demovote.tsv').then(function (text) {
        var data = vega.read(text, { type: 'tsv' });
        scatterplotTest.viewer.render(options, data);
    });
```

**Comment by danmarshall** [comment]
Hi @win32nipuh, we use Vega for layout, therefore we support the formats that Vega does: https://vega.github.io/vega/docs/data/#format
 > The currently supported data formats are json (the default), csv (comma-separated values), tsv (tab-separated values), dsv (delimited text files), and topojson.

**Comment by win32nipuh** [comment]
Thnx @danmarshall, I see. The question can be redirected to Vega. :-)

**Comment by Oleg26Dev** [comment]
By the way Vega developers wrote: a data can be loaded via Ajax request.
