### ISSUE TITLE
Context Menu item not showing up in OSx - cant start SandDance

### ISSUE THREAD

**Issue by veritas718** [microsoft/SandDance#123]
When using VI Studio in OSX, right-clicking on a csv file doesn't show the context menu item to view in SandDance. Im not sure how to start using it otherwise.

**Comment by veritas718** [comment]
It works just fine when looking at the files in a folder, but it would be nice if the "View in SandDance" menu item showed up for open editor files too.

**Comment by danmarshall** [comment]
I believe it does, if you right click on the tab. Where are you not seeing it?

**Comment by ian-rubenstein-mpf** [comment]
> I believe it does, if you right click on the tab. Where are you not seeing it?

Thanks for pointing that out too. Wasn't aware. The last place I would include it is on the [usually] left panel, under the list of open files in the space called _Open Editors_ 
![image](https://user-images.githubusercontent.com/25467862/67479197-8f513000-f62b-11e9-8749-8c324b5c351c.png)
