### ISSUE TITLE
vs code can't show chinese

### ISSUE THREAD

**Issue by cjd9023** [microsoft/SandDance#127]
how can i fix this , where can set charset on vscode ?  thansk
![image](https://user-images.githubusercontent.com/11306473/67491364-666e8080-f6a7-11e9-9bc7-ebe606bb14e8.png)

**Comment by danmarshall** [comment]
Hello, thank you for posting. Can you tell me, does this reproduce in the [online app](https://sanddance.js.org/app/)?

**Comment by cjd9023** [comment]
@danmarshall ,online app seems fine.
![image](https://user-images.githubusercontent.com/11306473/67528290-b1aa8280-f6eb-11e9-9afd-5454676c9abd.png)

**Comment by cjd9023** [comment]
C:\Users\XXXX\.vscode\extensions\msrvida.vscode-sanddance-1.2.12\resources
sanddance-explorer.js
line: 
![image](https://user-images.githubusercontent.com/11306473/67528628-883e2680-f6ec-11e9-8086-9ec4a6454414.png)

**Comment by danmarshall** [comment]
There are 2 levels of this bug. The screenshot addresses the existing bug #78 which refers to the characters in the WebGL canvas. The second bug is with the HTML also not showing the Chinese character set (red areas in original screenshot.)
