### ISSUE TITLE
Legend and Tooltips visualization problem

### ISSUE THREAD

**Issue by win32nipuh** [microsoft/SandDance#129]
Legend and Tooltips: white on light grey, it looks like they are empty. 
My application is: ASP.NET Core 2.2 +Electron.NET application. The SandDance works fine but now the problem is  Legend and Tooltips visualization.
How to fix it?

**Comment by danmarshall** [comment]
You can add your own style sheet to your page. The elements have css class names prefixed with `sanddance-`

**Comment by Oleg26Dev** [comment]
ok, thnx, but in any case it is interesting why this colors combination is used in my case.

**Comment by win32nipuh** [comment]
It loads these files ok as ASP.NET  does it.

**Comment by danmarshall** [comment]
Closing for now, please re-open if the issue persists.
