### ISSUE TITLE
Cubes are randomly slightly offset

### ISSUE THREAD

**Issue by Timmmm** [microsoft/SandDance#132]
For example in [the demo app](https://sanddance.js.org/app/):

![image](https://user-images.githubusercontent.com/376842/67860161-13685380-fb15-11e9-8596-19e9fb7a5b11.png)

Is this deliberate? Floating point error?

**Comment by danmarshall** [comment]
Hi @Timmmm, I've seen this happen at times also. Can you try entering, then exiting 3D mode to see if that fixes it?

**Comment by Timmmm** [comment]
That definitely improves things but I'm not 100% sure it fixes it. Another thing I've noticed, is that in 2D mode the rects are actually still cubes! I guess this meant you didn't have to write another whole layer for rects.... but I'm not sure why they still have thickness and the projection isn't 100% orthographic.

![image](https://user-images.githubusercontent.com/376842/67930428-aa85e780-fbb7-11e9-8d8e-3734acced884.png)

(note the corner)

Also if I'm only interested in 2D, won't rendering cubes be several times slower since you have 6 times as many faces? I can't get above 100k cubes performing well on my laptop. It's a Macbook Pro with Intel Iris Pro graphics - probably not the fastest, but I can do up to 1 million quads at 50 fps using desktop OpenGL.

**Comment by Timmmm** [comment]
Ah regarding the cube depth, it [seems to be deliberate](https://github.com/microsoft/SandDance/blob/41dd47356a02acd52a69927573885883d0c02624/packages/sanddance/src/vega-deck.gl/marks/rect.ts#L25) presumably *because* they are cubes and you don't want their front and back faces interfering. And presumably using perspective makes it easier to animate from 2D to 3D and back.

Still you *can* animate from orthographic to perspective and back, so I think it should do that. And it looks like you can just switch out [this line](https://github.com/microsoft/SandDance/blob/master/packages/sanddance/src/vega-deck.gl/cube-layer/cube-layer.ts#L125) to get rects?

**Comment by danmarshall** [comment]
Yes as you've suspected it's all about making the transitions smooth, which is why rects are actually flat cubes and 2d isn't 100% orthographic. We saw a few bugs when we didn't do it this way. Perhaps in v7 of deck.gl these might not be an issue, and we can revisit when we upgrade.

**Comment by danmarshall** [comment]
Can you try and repro in our new beta version?
https://sanddance.js.org/app-3.0.0-beta.1/
It's now using deck.gl version 8
