### ISSUE TITLE
PowerBI: Allow Visual Level Cross filtering

### ISSUE THREAD

**Issue by snapper911T** [microsoft/SandDance#133]
Using the current version of SandDance for Power BI I cannot select a point/bar/mark in the sand dance visual and filter another chart on the same tab. I **can** select a bar on a non SandDance chart and it will filter the SandDance visual...but would like it to work the other way as well.

**Comment by danmarshall** [comment]
Thanks for posting. Can you share a screenshot showing the configuration of your Power BI report?

**Comment by snapper911T** [comment]
Sure, its a pretty simple example. I would expect clicking on fleet 1 in the sanddance visual to filter the barchart to fleet1 as well.
![Screenshot (352)](https://user-images.githubusercontent.com/43861167/67920521-c8286200-fb61-11e9-9791-bf5d91ce82bd.png)

**Comment by snapper911T** [comment]
Any hope this would be pushed out soon? I have a use case in which it would be helpful to have this functionality.

**Comment by danmarshall** [comment]
You can achieve this when you filter in SandDance. To do so:
1. Click the item.
1. You should see Selected: 1 in the data counter.
1. Click the Isolate button at the top.

**Comment by snapper911T** [comment]
Would be beneficial if we didn't have to go through so many steps to do it. Also, Your solution requires me to expose the SandDance chrome controls/settings to an end user which is not ideal.

**Comment by danmarshall** [comment]
Hi @snapper911T , this is now in a PR, it may take a week or more to get it to the PowerBI marketplace.

**Comment by snapper911T** [comment]
Wow, thats awesome! I wish I could get the Charticulator team to be this responsive :)

**Comment by danmarshall** [comment]
This in now live in PowerBI as of version 1.3.8

**Comment by snapper911T** [comment]
You rock!! THANKS!

**Comment by danmarshall** [comment]
Hi @snapper911T , another user requesting this same functionality has pointed out an issue, when the selection contains thousands of data points. This causes the PowerBI UI to hang for several minutes. So, we will re-implement this as a filter instead of selection. I believe this behavior will still fulfill your original scenario.
