### ISSUE TITLE
Add 360 degree rotation possible on y-axis

### ISSUE THREAD

**Issue by Subarna578** [microsoft/SandDance#134]
SandDance is amazing. However, I couldn't find the option to see the base part of graph from below. The rotation is limited to around 250 degree in y axis Things we can do are
1) Zoom in , zoom out
2) Rotate 360 degree in x axis
So my issue is regarding 360 degree rotation in y axis too in order to see the holistic picture of the graph.
![270 degree rotation max possible](https://user-images.githubusercontent.com/46166034/68006688-70901080-fc9f-11e9-95b6-efb726a63211.png)

**Comment by danmarshall** [comment]
Hello, thanks for the feedback. You can orbit by holding shift while you drag. Or if you drag with your right mouse button. Sorry that it wasn’t more easily discoverable, we will need to add a small help screen for this. Cheers

**Comment by danmarshall** [comment]
Oh I see, you would like to rotate below the ground plane. We will need to see if deck.gl’s OrbitController will allow this...

**Comment by Subarna578** [comment]
Thanks danmarshall. I will look at it.

**Comment by danmarshall** [comment]
We have a new rendering engine which allows full rotation of the graph, please try the latest :)
