### ISSUE TITLE
Visual Studio Code is crashed with large data size

### ISSUE THREAD

**Issue by BigtoC** [microsoft/SandDance#141]
I tried to visualize a csv file with 106 columns and 13245 rows, after a short loading, visual studio was crashed. My system information is shown in the second picture.

![crashed](https://user-images.githubusercontent.com/33389684/68448790-a6913f80-021f-11ea-9422-3a575e7c2f82.png)

![system-info](https://user-images.githubusercontent.com/33389684/68448812-bad53c80-021f-11ea-8894-35376b9d4f14.png)

**Comment by danmarshall** [comment]
Thanks @BigtoC for the bug report. Can you tell us the schema of these 106 columns - are they numeric or strings?

**Comment by BigtoC** [comment]
> Thanks @BigtoC for the bug report. Can you tell us the schema of these 106 columns - are they numeric or strings?

You can find those data in this url:
https://www.kaggle.com/thoroc/edinburgh-inside-airbnb#listings.csv
It contains number and strings, some are chinese.

![Screenshot_20191109-151919](https://user-images.githubusercontent.com/33389684/68524687-b2a2fd00-0304-11ea-81e9-640f9eef732e.jpg)

**Comment by Yerne** [comment]
Crashed with large file, mixed data types, 304 columns.

**Comment by danmarshall** [comment]
Thanks all for the extra info. Let's continue the conversation in #119
