### ISSUE TITLE
fixed legend range

### ISSUE THREAD

**Issue by mzy2240** [microsoft/SandDance#142]
Howdy, do you know how to fix the legend? The values in the legend always change, and I tried to change the legend directly but it will not render anyway. Thanks!

**Comment by danmarshall** [comment]
Hello @mzy2240  can you please provide perhaps a screenshot and more detail of what you are trying to achieve?

**Comment by mzy2240** [comment]
@danmarshall Hey Dan, I'm trying to make it work with real time data. Now everything is working, unless the values in the legend keep changing.  For example, at beginning all data are within 1-1.2 which is the safe zone, so the color should be all blue; and later some data starts to drop so they should become red or something. However,  right now because the legend value keeps changing, so all the points are always blue to red, so color becomes meaningless.

**Comment by danmarshall** [comment]
Thanks for the clarification @mzy2240 . Realtime is a scenario we haven't necessarily considered yet. Which component are you using?

**Comment by mzy2240** [comment]
@danmarshall I'm using the pure SandDance core with Vue.

**Comment by danmarshall** [comment]
Just a thought: perhaps you can prime your dataset with a couple of rows of data which specify the min and max of the range.

**Comment by mzy2240** [comment]
Is it possible to pass a fixed a legend option when calling the render function?

**Comment by danmarshall** [comment]
Well, you can always just hide the legend and render your own.

**Comment by mzy2240** [comment]
However, hide the legend will still change the colormap

**Comment by mzy2240** [comment]
what if I want to have a colormap for data over 1 even if there is no data in that range?

**Comment by danmarshall** [comment]
Sorry, I forgot that you can intercept the intermediary scenegraph prior to rendering. 
In your [options](https://github.com/microsoft/SandDance/blob/master/docs/docs/sanddance/v1/api/types.md#vieweroptions), add an `onStage` handler. The [stage](https://github.com/microsoft/SandDance/blob/master/docs/docs/sanddance/v1/api/vegadeckgl.types.md#stage) object will contain the `legend` that you may modify. Sorry that some of these docs are not linkink correctly. 😐

**Comment by mzy2240** [comment]
Thanks a lot! Yeah thats another issue I want to report.  Most of the doc links are btoken, it's really hard to code without doc.

**Comment by danmarshall** [comment]
Hello, we've got new docs. If this is still an issue, please feel free to re-open it.
