### ISSUE TITLE
How to draw map of UK?

### ISSUE THREAD

**Issue by ZedZipDev** [microsoft/SandDance#145]
I have a database, one of tables contain client list with addresses+UK Postcode.
I'd like to draw map of UK and display diagram with amount of clients in each UK region.
What should I use? Any template? Thanks for ideas.

**Comment by RandomFractals** [comment]
I would suggest you use Vega and sift through their maps examples.

You can try Vega examples with my Vega Viewer ext. for vscode :)

https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-vega-viewer

**Comment by danmarshall** [comment]
Our viewer does not currently render Vega-based maps. It may be possible to use the maps underlying [deck.gl](https://deck.gl). Can you tell me which component you are using? e.g. sanddance, sanddance-react, sanddance-explorer ?

**Comment by RandomFractals** [comment]
also, I believe Observable HQ has some UK maps you can pull some code bits from ;)

https://observablehq.com/search?query=UK%20map

**Comment by RandomFractals** [comment]
on my todo list for data preview too :(

https://github.com/RandomFractals/vscode-data-preview/issues/7

**Comment by danmarshall** [comment]
Hello, you can now use a rasterized image as a background:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/11507384/212202176-dc8ac70b-3c49-4b41-9469-39027eec3097.png">
