### ISSUE TITLE
feature request : export to html

### ISSUE THREAD

**Issue by djouallah** [microsoft/SandDance#15]

**Comment by danmarshall** [comment]
Hello, can you provide details? What should be exported?

**Comment by djouallah** [comment]
Data and visualisations, for an example see kepler.gl

**Comment by danmarshall** [comment]
Hi @djouallah - This seems like 2 feature requests. Let's look at the each:
* Data export - We provide 2 sample datasets. Other than that, it's your own data. Not sure why SandDance would be exporting that which you already have? Are you looking to export the filtered data? 
* Visualization export - Is a screenshot good enough? Are you looking for a higher resolution image?

**Comment by djouallah** [comment]
sorry, was not clear

I meant export an HTML that include the visuals and the data inline,  basically a standalone self contained HTML.

screenshots is not enough as it is not interactive.

**Comment by danmarshall** [comment]
Is offline access required? If not, you might be able to use the snapshot feature:
![image](https://user-images.githubusercontent.com/11507384/56516857-658a4580-64f0-11e9-9be5-f1d4cffa2d50.png)

This lets you create a deep link to a filtered chart, [like this](https://microsoft.github.io/SandDance/app/#{%22description%22:%22Texas%22,%22insight%22:{%22colorBin%22:%22continuous%22,%22columns%22:{%22uid%22:%22Id%22,%22x%22:%22Longitude%22,%22y%22:%22Latitude%22,%22color%22:%22Obama%22,%22z%22:%22Education%22,%22sort%22:%22State%22,%22size%22:%22TotalPop%22},%22facets%22:null,%22filter%22:{%22expressions%22:[{%22key%22:0,%22name%22:%22State%22,%22operator%22:%22==%22,%22value%22:%22Texas%22,%22errorMessage%22:null}]},%22scheme%22:%22redblue%22,%22signalValues%22:{%22SandDanceZProportion%22:0.6,%22SandDanceTextScale%22:2,%22SandDanceTextAngleX%22:30,%22SandDanceTextAngleY%22:0,%22SandDancePointSize%22:11,%22SandDanceColorBinCount%22:2},%22size%22:{%22height%22:942,%22width%22:1294},%22chart%22:%22scatterplot%22,%22view%22:%222d%22},%22dataSource%22:{%22dataSourceType%22:%22sample%22,%22id%22:%22demovote%22,%22displayName%22:%22Demo%20Vote%22,%22dataUrl%22:%22https://microsoft.github.io/SandDance/sample-data/demovote.tsv%22,%22type%22:%22tsv%22}})

**Comment by djouallah** [comment]
ok, so how  this works with my own data, where my data is saved ?

**Comment by danmarshall** [comment]
Easiest is if your data is accessible via url. Can you run a local web server? 
For example https://www.npmjs.com/package/local-web-server

If not, then much more machinery would be involved.

**Comment by djouallah** [comment]
unfortunately no, no web server and the data is private, hence the standalone HTML

cheers Mate

**Comment by danmarshall** [comment]
Hi @djouallah - I'm looking at [Altair's export to HTML feature](https://altair-viz.github.io/user_guide/saving_charts.html#html-format) and the [example chart](https://altair-viz.github.io/_static/chart.html), which is a somewhat static chart.

Are you looking for just the SandDance chart, or are you looking for the full explorer with all the chrome?

![image](https://user-images.githubusercontent.com/11507384/56537340-21f60280-6515-11e9-83d3-ddf140d29dc6.png)

**Comment by djouallah** [comment]
the full explorer with the data inline, the user interact with the visyals and filter and do stuff, but not necessary upload new data.

for altair, here is an example I made, it is fully interactive

https://djouallah.github.io/vega-lite/

**Comment by danmarshall** [comment]
Seems the data is online, in a gist:
![image](https://user-images.githubusercontent.com/11507384/56537912-8cf40900-6516-11e9-8a75-af34d65c96b9.png)

**Comment by djouallah** [comment]
here is the same example with inline data
https://gist.github.com/djouallah/a0bc3b62105f5d2a0223cbb98f10047f

**Comment by danmarshall** [comment]
Linking this to #36 as it seems related

**Comment by danmarshall** [comment]
Thanks for the feature request. This is now live at https://sanddance.js.org/app/

find the export button at the bottom of the Data Browser tab:
![image](https://user-images.githubusercontent.com/11507384/66964361-2f56fa00-f02b-11e9-8421-b6745b212a37.png)

Then, choose HTML as your file format.

**Comment by djouallah** [comment]
thank you fantastic !!!!!!

**Comment by Timaos123** [comment]
> Thanks for the feature request. This is now live at https://sanddance.js.org/app/
> 
> find the export button at the bottom of the Data Browser tab: ![image](https://user-images.githubusercontent.com/11507384/66964361-2f56fa00-f02b-11e9-8421-b6745b212a37.png)
> 
> Then, choose HTML as your file format.

hi,why don't I have this button?

**Comment by Timaos123** [comment]
> Thanks for the feature request. This is now live at https://sanddance.js.org/app/
> 
> find the export button at the bottom of the Data Browser tab: ![image](https://user-images.githubusercontent.com/11507384/66964361-2f56fa00-f02b-11e9-8421-b6745b212a37.png)
> 
> Then, choose HTML as your file format.

Hi, why don't I have this button?

![image](https://user-images.githubusercontent.com/31198670/196171734-116b84d6-3c88-4763-abf5-8200cb58978f.png)

**Comment by danmarshall** [comment]
@Timaos123 this capability is part of our web app but is not built in to the sanddance-explorer or sanddance-embed components (as not all contexts allow “downloads”). Where/how are you using SandDance?
