### ISSUE TITLE
Using Sanddance Explorer in a React application

### ISSUE THREAD

**Issue by casperOne** [microsoft/SandDance#155]
First, I want to say thank you for this library; it looks like it has amazing potential, and could give many people the ability to explore their data.

That said, the documentation and examples seem to be non-existent; as a result, I'm finding it very difficult to get a simple example off the ground.

Here's the scenario I have; I have a set of data that I've downloaded/obtained from the server.  It's a set of Javascript objects, but if necessary, I can get it from the server in JSON, CSV, whatever.

The desire is to take that data and make it available in an instance of the Sanddance explorer.

My thought is that it is as easy as creating an instance of `Explorer` and then passing the data along with column descriptors to it, but I can't seem to find a way to do that.  The [`DataContent` type](https://sanddance.js.org/docs/sanddance-explorer/v2/api/#datacontent) implies there's some type to help provide and describe data, but I see no way of passing it to the `Explorer` instance.

Is there an example out there that shows how to do this?

**Comment by casperOne** [comment]
Here's a code sandbox with the most recent error:

````
Cannot read property 'Spinner' of null
````

https://codesandbox.io/s/keen-architecture-5s2qy

Also, is version 2 of the explorer stable?  It looks like the call to `SandDance.use` bombs (causing the page to just be blank) when using version 2 of `@msrvida/sanddance-explorer`.

If I use version 1.7.1 I can at least get to the Spinner error above.

**Comment by danmarshall** [comment]
Hi @casperOne , thanks for filing this issue, and sorry about the delay - I was on vacation 🌴.
Looks like I have made a couple of omissions. Here is the new sample code I will be adding to the readme:

We use the office-ui-fabric-react package for our common controls. Add this to your package.json:
```
"office-ui-fabric-react": "6.204.4",
```

```js
import * as deck from '@deck.gl/core';
import * as layers from '@deck.gl/layers';
import * as luma from 'luma.gl';
import * as fabric from 'office-ui-fabric-react';
import * as vega from 'vega';
import { Explorer, use } from '@msrvida/sanddance-explorer';

fabric.initializeIcons();

use(fabric, vega, deck, layers, luma);

const data = [
  { a: 1, b: "c1" },
  { a: 1, b: "c2" },
  { a: 2, b: "c3" },
  { a: 3, b: "c4" }
];

const explorerProps = {
    logoClickUrl: 'https://microsoft.github.io/SandDance/',
    mounted: explorer => {
        explorer.load(data);
    }
};

ReactDOM.render(React.createElement(Explorer, explorerProps), document.getElementById('app'));
```
 Also, it seems I neglected to publish the chart-recommender 2.0 dependency, so the 2.0 version should be stable now. Please let me know if this gets you up and running.

**Comment by casperOne** [comment]
@danmarshall Thanks for the response (and this is OSS, so there is not an expectation of a response on this end, and there is no reason to apologize for vacation).

I've been able to get the app to run without crashing (but not without issues):

https://codesandbox.io/s/sanddance-js-demo-wwyv1

However, there are some additional things I had to do:

- You need to reference the CSS for explorer (`import "@msrvida/sanddance-explorer/dist/css/sanddance-explorer.css"`).
- `luma.gl` has to use version 6.4.3; otherwise, there is a conflict with another library which is using luma (you can see this in the console if you explicitly reference 6.4.0).

However, I get a screen that only shows the legend:

![image](https://user-images.githubusercontent.com/561862/71389341-04a89500-25ca-11ea-95c9-edaa9f17079f.png)

When I look in the console, I see the following two errors:

````
proxyConsole.js:64 selections-fill-top  Bad uniform project_uViewProjectionMatrix (16) [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]

Uncaught Error: selections-fill-top  Bad uniform project_uViewProjectionMatrix
    at checkUniformValues (uniforms.js:216)
    at Program.setUniforms (program.js:255)
    at Model.setUniforms (model.js:332)
    at Model.updateModuleSettings (model.js:363)
    at SolidPolygonLayer.setModuleParameters (layer.js:1034)
    at SolidPolygonLayer.drawLayer (layer.js:859)
    at drawLayerInViewport (draw-layers.js:306)
    at eval (draw-layers.js:255)
    at Array.forEach (<anonymous>)
    at drawLayersInViewport (draw-layers.js:227)
    at eval (draw-layers.js:113)
    at Array.forEach (<anonymous>)
    at drawLayers (draw-layers.js:107)
    at eval (draw-layers.js:157)
    at withParameters (context-state.js:238)
    at drawPickingBuffer (draw-layers.js:151)
    at drawAndSamplePickingBuffer (pick-layers.js:234)
    at pickObject (pick-layers.js:78)
    at LayerManager.pickObject (layer-manager.js:391)
    at DeckGLInternal._pickAndCallback (deck.js:492)
    at DeckGLInternal._onPointerMove (deck.js:765)
    at EventRegistrar._emit (event-registrar.js:118)
    at EventRegistrar.handleEvent (event-registrar.js:92)
    at Manager.emit (hammer.js:2631)
    at EventManager._onOtherEvent (event-manager.js:312)
    at MoveInput.handleMoveEvent (move-input.js:141)
    at MoveInput.handleEvent (move-input.js:79)
````
Is there something I'm missing here?

(side note: there's a few hundred source map warnings of the type:

````
DevTools failed to parse SourceMap: https://wwyv1.csb.app/node_modules/office-ui-fabric-react/lib-commonjs/components/SwatchColorPicker/SwatchColorPicker.styles.js.map
````

but this looks to be an issue with `office-ui-fabric-react` so I'll file an issue there)

**Comment by danmarshall** [comment]
I believe that you only need to specify the canvas size. Can you try adding this to your CSS:
```css
.sanddance-explorer {
  height: 800px; /*whatever height you need */
}
```

**Comment by casperOne** [comment]
@danmarshall That was it, thank you!  Much appreciated.

**Comment by casperOne** [comment]
Some additional details for others.

If you are using [yarn](https://yarnpkg.com/lang/en/) as your package manager, then you need to get the 6.4.10 versions of `@deck.gl/core` and `@deck.gl/layers`.

`@deck.gl/layers` has a caret range version reference to `@deck.gl/core` version `^6.4.0`; when yarn tries to get the absolute version number, it resolves it to the latest version of 6.4, which is 6.4.10.

This is important because `@deck.gl/core` will detect that there are two different versions and fail with just a warning in the logs.

**Comment by casperOne** [comment]
@danmarshall Unfortunately when I try and take the code from the sandbox into my application, I am getting the spinner fail issue.  I am going to try and debug further.

**Comment by casperOne** [comment]
Ok, I figured it out, the import of `use` is super-important, as it sets up the components from the Office React UI library; if you call `use` on `SandDance` (as I was doing in my code, and not the sandbox), then it gives you the spinner error.

Thanks again!

**Comment by hydrosquall** [comment]
Hi @casperOne , it looks like the sandbox recently stopped working (https://codesandbox.io/s/sanddance-js-demo-wwyv1). I looked inside the explorer, but I'm not sure where exactly the code is throwing in the unminified code since `AllData` only ever exists on an enum (which is constant). Any idea what might be happening?

https://a.cl.ly/qGuogQGo

**Comment by danmarshall** [comment]
@hydrosquall - please see the update on #196 - CodeSandbox has made a fix.
