### ISSUE TITLE
Cannot compile SandDance create-react-app with TypeScript

### ISSUE THREAD

**Issue by casperOne** [microsoft/SandDance#156]
Even though I can't find an explicit declaration that SandDance supports typescript, it is implied:

![image](https://user-images.githubusercontent.com/561862/71049552-ae8eaa00-2110-11ea-8576-c2d4b95efcc7.png)

That said, the following libraries don't have TypeScript typings:

- `@deck.gl/core`
- `@deck.gl/layers`
- `luma.gl`

So when trying the example from the main documentation page:

````
import * as deck from '@deck.gl/core';
import * as layers from '@deck.gl/layers';
import * as luma from 'luma.gl';
import * as vega from 'vega';
import { Explorer, SandDance } from '@msrvida/sanddance-explorer';

SandDance.use(vega, deck, layers, luma);
````

We get the following TypeScript compiler error:

````
Could not find a declaration file for module '@deck.gl/core'. 'c:/d/One-Frame-Link-Data/src/OflData.Website.EntryPoint/ClientApp/node_modules/@deck.gl/core/dist/es5/index.js' implicitly has an 'any' type.
  Try `npm install @types/deck.gl__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@deck.gl/core';`  TS7016
````

The package `@deck.gl/gl__core` doesn't exist.

The example *should* be:

````
// @ts-ignore
import * as deck from '@deck.gl/core';
// @ts-ignore
import * as layers from '@deck.gl/layers';
// @ts-ignore
import * as luma from 'luma.gl';
import * as vega from 'vega';
import { Explorer, SandDance } from '@msrvida/sanddance-explorer';

SandDance.use(vega, deck, layers, luma);
````

**Comment by danmarshall** [comment]
Hi @casperOne , these typings can be found here: https://github.com/danmarshall/deckgl-typings
```
npm install -D @danmarshall/deckgl-typings
```

**Comment by casperOne** [comment]
@danmarshall This is it, thank you!

**Comment by RandomFractals** [comment]
i.e. update your tsconfig.json ... ;)

**Comment by Vicky522** [comment]
> Hi @casperOne , these typings can be found here: https://github.com/danmarshall/deckgl-typings
> 
> ```
> npm install -D @danmarshall/deckgl-typings
> ```

Thank u <3
