### ISSUE TITLE
Chinese font not friendly display in Visual Studio Code

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [microsoft/SandDance#157]
demo.csv
---------
国家,频次
中国,110
美国,20
日本,10
England,15

-----结果
![image](https://user-images.githubusercontent.com/3310967/71397233-e5f0df80-2657-11ea-8882-ccb0e4b2b44a.png)

**Comment by danmarshall** [comment]
Possibly duplicate of #78

**Comment by feifeiiiiiiiiiii** [comment]
@danmarshall ok, I will close duplicate
