### ISSUE TITLE
Describing data loaded into SandDance Explorer

### ISSUE THREAD

**Issue by casperOne** [microsoft/SandDance#158]
Currently we are loading data through the `mounted` callback, calling `load` on the `Explorer` component and passing an array of objects.

It's clear that SandDance has some default logic for how to describe data; string values are categorical, numbers are quantifiable, etc.  Additionally, I imagine that SandDance does things like encoding the string values into numbers in order to speed operations.

However, in loading the data ourselves, we probably have (or can store/extend) metadata about our data to assist SandDance in this (as well as correct any false assumptions).

As an example, if we have rows of data, like so:

````
{
    id: 1,
    description: 'some thing',
    otherId: 4,
    category: 'car'
}
````

In this case, we know the following:

- `id` is unique, it's self categorizing
- `description` is unique (let's assume) and a numeric representation is _already_ encoded in `id`
- `otherId` is categorical, not quantitative, and we shouldn't allow aggregates on it
- `category` is categorical, and needs an encoding for it

That said, I see that there is a `Column` type in the TypeScript declarations which has some of that data (as well as min/max values, etc.).  I also see that there is a `DataContent` interface which has the data and `Column` types exposed, and this looks promising.

The question is, are there options for us to actually help SandDance explorer with this decision, or are these default assumptions the only choice we have?

**Comment by danmarshall** [comment]
Hi @casperOne thanks for bringing this up, you are the first to have gotten this deep in our API to expose the need to document it.

The `load` method accepts an additional parameter, a function which will be passed the column metadata. Here is an example:

```js
const getInsight = (columns) => {
  console.log(columns);
  columns[0].quantitative = false;
};

const explorerProps = {
  mounted: explorer => {
    explorer.load(data, getInsight);
  }
};
```

The `columns` parameter will be an array of Column metadata objects that you may modify. In your example, you may wish to find the column with the `name` of 'otherId' and set its `quantitative` property to false.

This topic deserves its own page in our docs...

**Comment by casperOne** [comment]
@danmarshall Thanks for the reply.

I had noticed that, but wasn't sure if the intent was to mutate in place (even though the callback's return type is `void`).

Thanks for the clarification.

**Comment by danmarshall** [comment]
Actually the callback can optionally return an `Insight` object, which tells it how to render a chart. For an example of this object, you can call `explorer.viewer.getInsight()` to see the params of the current chart view.

**Comment by casperOne** [comment]
@danmarshall 
Two issues:

1) It appears the typescript definition for the `getPartialInsight` callback isn't correct compared to your code in JS above.

Your code doesn't have any return type, so the signature would be (note, the parenthesis around the return type are *super* important here):

````
(columns: SandDance.types.Column[]) => (Partial<SandDance.types.Insight> | undefined)
````

However, the type definition in the file is:

````
(columns: SandDance.types.Column[]) => Partial<SandDance.types.Insight>
````

I can get around it currently using:

````
return undefined as any
````

Which gets around the compiler error, but it's a tad unsightly.

2) It appears this callback is called *after* the values/types are iterated over.  Is there any way to trust the provider to supply all/some of the required data?  I'm not sure to what degree `ColumnStats` is used, but we can certainly indicate if there are negative elements, min, max, etc.

On a somewhat related note to 2, I see `distinctValueCount` in `ColumnStats` is required, but `min`, `max`, etc. are not.  If the above is implemented (where we supply all the data), we may need to set this type to `number | undefined` to indicate we don't really know.

**Comment by danmarshall** [comment]
1. Will changing the return type of the signature to the following work?:
```
Partial<SandDance.types.Insight> | void
```
Then you won't need to `return undefined as any`.

2. You should be able to invoke `explorer.setState({ columns })` immediate after the `.load()` promise is resolved. Then you can change the columns as you see fit.

**Comment by casperOne** [comment]
@danmarshall That *would* work, but I'd argue it confuses things.

Using `<anything> | void` has this feeling of co-mingling functions with procedures which I don't see in JS/TS in the wild; either it returns a value (even if `undefined`) or it doesn't.

Additionally, the name of the callback is `getPartialInsight`, with an emphasis on the *get* part.  This implies it's a function and should return *something*, even if it's partial (or nothing at all, which is represented by `undefined`).

To be clear, the issue isn't with having to use `return undefined`, it's the casting of `undefined` to `any` in order to get around the mistyping of the method to begin with.

I think it would make much more sense to reason about if the signature was as I originally proposed:

````
(columns: SandDance.types.Column[]) => (Partial<SandDance.types.Insight> | undefined)
````

That way, the behavior is consistent (even if returning nothing, that's an explicit decision by the implementer).

**Comment by danmarshall** [comment]
I agree with your comments about the typings. Have you seen the latter part of my reply?:
> You should be able to invoke `explorer.setState({ columns })` immediate after the .load() promise is resolved. Then you can change the columns as you see fit.

If that works then we don't need to change the signature, as you would no longer need to provide `getPartialInsight`.

**Comment by casperOne** [comment]
@danmarshall Apologies, I did see that; we may try that; we have it working for now, setting the values on the `Insight`, so no need to trim it.  I see the fix of the TS definitions as nice-to-have and not a blocker.

We may use that call for other things, however, so thank you for showing there is more than one way to approach the issue.
