### ISSUE TITLE
Last series in BAR graphs lumps last groups together

### ISSUE THREAD

**Issue by LloydOsborn-GB** [microsoft/SandDance#166]
Created a chart with Years as the Y axis.

2019 was the last number on the Y access, but bar contained 2020.

Filtered out 2020 as a year and the last bar was comprised of 2018 and 2019 data.

![Bug Sandance Years mixed on Bar](https://user-images.githubusercontent.com/35978198/72018922-3d817480-322e-11ea-984c-600f7118e721.PNG)

**Comment by danmarshall** [comment]
I'm not able to repro this - can you provide a sample dataset?

**Comment by danmarshall** [comment]
Closing this for now. Please reopen if this occurs in the latest version and you're able to provide a data sample for repro.
