### ISSUE TITLE
Facet Label Overlapping

### ISSUE THREAD

**Issue by nami-cagla** [microsoft/SandDance#178]
Hi! I am currently trying to recreate the SandDance app example on https://sanddance.js.org/app/ within a Nuxt.js project.

I made the facet by work, but whenever I facet by, all the labels are just stuck in the upper left corner of the chart, and I'm not sure how I can move them on top of each chart??

Sample:
![facet](https://user-images.githubusercontent.com/59039396/72871112-5bba9a80-3d2d-11ea-8931-321c9637d7f4.png)

**Comment by danmarshall** [comment]
Can you tell me which version of SandDance & which version of Vega ?

**Comment by nami-cagla** [comment]
Sanddance - 1.6.7 and Vega - 5.8.1

**Comment by danmarshall** [comment]
Ok, This needs to go into our documentation:
* SandDance 1 uses Vega 4
* SandDance 2 uses Vega 5
Sorry about the confusion.

**Comment by nami-cagla** [comment]
It works! Thank you so much for your help!

**Comment by nami-cagla** [comment]
It works! Thank you so much for your help!

**Comment by danmarshall** [comment]
Thanks for your patience!
