### ISSUE TITLE
Axis bin size and ranges

### ISSUE THREAD

**Issue by CAGLADJ** [microsoft/SandDance#184]
When working with numeric columns, the bin size of the x axis (or y axis depending on the chart type) which is selected/shown in the UI is not the same as shown in the graph.

For example: I have a numeric column with the unique values 1, 2, 3, 4, 5

With this data, the bin size results to the following (UI: graph (bin values)):
1: 1 (0)
2-3: 3 (0, 2, 4)
4-7: 4 (1, 2, 3, 4)
8-19: 8 (1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5)
20: 20 (1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4. 2.6, 2.8, 3, 3.2, 3.4, 3.6, 3.8, 4, 4.2, 4.4, 4.6, 4.8)

Through which settings is it possible to split the bin ranges more nicely, so that there are 5 bins, when selecting 5?

Also, why is 5 not shown on the axis as a value? The data points with the value 5 are always shown in the bin for 0, 4, 4.5, 4.8 depending on the bin size.

**Comment by danmarshall** [comment]
Hi @CAGLADJ , looks like we should rename the label which is misleading - it should be "max bins" instead of "bins". 
The fact that "5" is not a bin, is a bug. I will investigate. We have an upcoming change that should take of this hopefully.

**Comment by CAGLADJ** [comment]
@danmarshall Thank you for looking into it. I guess, then I will have to wait for the change.

**Comment by danmarshall** [comment]
This was fixed in #341, thanks!
