### ISSUE TITLE
Importing Local Data

### ISSUE THREAD

**Issue by kellykvu** [microsoft/SandDance#186]
Hello,
On the sample app, there is the option to 'Use your own data'.
![image](https://user-images.githubusercontent.com/40072612/74287740-4b745a80-4cf0-11ea-8822-e25edd6fe07e.png)

On my local version of sanddance-explorer, I don't see that option. How do I include this?
![image](https://user-images.githubusercontent.com/40072612/74287856-92fae680-4cf0-11ea-80ea-38da96484a78.png)

**Comment by danmarshall** [comment]
Hello, is your local version an HTML export? Or the VSCode extension?

**Comment by kellykvu** [comment]
It's a local react app with the sample code from sanddance-explorer.

**Comment by danmarshall** [comment]
You can pass a `datasetElement` in your props to `Explorer`.
https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/src/explorer.tsx#L72

The online SandDanceApp's button source is here:
https://github.com/microsoft/SandDance/blob/master/packages/sanddance-app/src/dataSourcePicker.tsx

**Comment by kellykvu** [comment]
Thank you! That helped and I am able to load my own data now.

I'm interested in including the Dark/Light theme button in my version of Sanddance.
![image](https://user-images.githubusercontent.com/40072612/77690181-e5c2f180-6f70-11ea-9b05-7f35fc985f77.png)
 
I've tinkered around and included 
      theme: 'dark-theme',
in my explorerProps but it's not coming out too readable:
![image](https://user-images.githubusercontent.com/40072612/77690625-992be600-6f71-11ea-95b6-1bb93fd1b0a1.png)
Any guidance would be appreciated.

**Comment by danmarshall** [comment]
The dark theme needs to be passed to 3 component areas:
* The SandDance Viewer (as ViewerOptions)
* The SandDance Explorer props (you have this already!)
* Office Fabric UI

Take a look at [how its done for the SandDanceApp on the web](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-app/src/sanddanceApp.tsx#L218) and [how its done for the VSCode extension](https://github.com/microsoft/SandDance/blob/master/packages/common-extensions/src/app.tsx#L97)

**Comment by danmarshall** [comment]
Closing this issue for now, please feel free to re-open if necessary.
