### ISSUE TITLE
sanddance react can't show tooltips

### ISSUE THREAD

**Issue by wmydz1** [microsoft/SandDance#187]
class SandDanceView extends React.Component {
    
    render() {

        var insight = {
            columns: {
                color: 'price',
                sort: 'createTime',
                uid: 'buyOrderVolume',
                x: 'createTime',
                y: 'price',
                z: 'volume'
            },
            scheme: 'redblue',
            size: {
                height: 2500,
                width: 2000
            },
            chart: 'scatterplot',
            view: '3d'
        };
        

        return (
                <SandDanceReact insight={insight} data={data} />
        )

    }
}

**Comment by danmarshall** [comment]
Hello, I cannot reproduce this. I created a new `create-react-app` app and added your code:
![image](https://user-images.githubusercontent.com/11507384/74970393-26a87300-53d3-11ea-800a-51435673ae3a.png)

Can you try adding a breakpoint in `onCubeHover`:
![image](https://user-images.githubusercontent.com/11507384/74970216-d6c9ac00-53d2-11ea-9617-03a3f6a3d452.png)

Then you can inspect the element to see why it is not appearing:
![image](https://user-images.githubusercontent.com/11507384/74970593-7edf7500-53d3-11ea-8017-ea722b457d36.png)

**Comment by wmydz1** [comment]
it works fine in firefox. but I can't find the tooltip in chrome (79.0.39)

**Comment by danmarshall** [comment]
Do you see tool tips in https://sanddance.js.org/app/ in your Chrome?

**Comment by wmydz1** [comment]
yes, I can see the tooltip in https://sanddance.js.org/app/ in my Chrome. but I can't see it in react app. it just works in firefox and Microsoft edge, it doesn't work in Chrome

**Comment by wmydz1** [comment]
The tooltip's background is dark in   https://sanddance.js.org/app/ , but the tooltip is transparent in the react app in my firefox.

**Comment by danmarshall** [comment]
Can you share your project?

**Comment by danmarshall** [comment]
Hello @wmydz1 - is this still an open issue?
