### ISSUE TITLE
Error with fresh create-react-app

### ISSUE THREAD

**Issue by t-book** [microsoft/SandDance#191]
Hi,

I'm trying to give sanddance explorer a test run. Unfortunately it fails to start. This is what I did:

```
npx create-react-app sd-test
cd sd-test/
# edit pagacke.json
npm start
```

This is what my dependencies look like:

```
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-scripts": "3.4.0",
    "@deck.gl/core": "6.4",
    "@deck.gl/layers": "6.4",
    "@msrvida/sanddance-explorer": "^2",
    "luma.gl": "6.4",
    "office-ui-fabric-react": "6.204.4",
    "vega": "^5.8"
  },
```

and my index.js

```
import React from 'react';
import ReactDOM from 'react-dom';

import * as deck from '@deck.gl/core';
import * as layers from '@deck.gl/layers';
import * as luma from 'luma.gl';
import * as fabric from 'office-ui-fabric-react';
import * as vega from 'vega';
import { Explorer, use } from '@msrvida/sanddance-explorer';

fabric.initializeIcons();

use(fabric, vega, deck, layers, luma);

const data = [
  { a: 1, b: "c1" },
  { a: 1, b: "c2" },
  { a: 2, b: "c3" },
  { a: 3, b: "c4" }
];

const explorerProps = {
    logoClickUrl: 'https://microsoft.github.io/SandDance/',
    mounted: explorer => {
        explorer.load(data);
    }
};

ReactDOM.render(React.createElement(Explorer, explorerProps), document.getElementById('root'));
```

Both from the docs. On startup it fails with following console error:

![Bildschirmfoto 2020-03-12 um 08 01 09](https://user-images.githubusercontent.com/20478652/76495689-a7d5b180-6437-11ea-89a1-d251994630a6.png)

What am I'm doing wrong?
Thanks a lot for your help!

**Comment by danmarshall** [comment]
Hello, I believe you're almost there! You may need to specify a canvas size, please see this thread:
https://github.com/microsoft/SandDance/issues/155#issuecomment-568814187

**Comment by t-book** [comment]
good shoot @danmarshall  but unfortunately the error stay the same ;(

**Comment by t-book** [comment]
This is how the error shows up on screen:

![Bildschirmfoto 2020-03-12 um 20 52 59](https://user-images.githubusercontent.com/20478652/76561406-89a59b00-64a3-11ea-8f4d-eeb258866ace.png)

**Comment by danmarshall** [comment]
Can you add:
```js
import "@msrvida/sanddance-explorer/dist/css/sanddance-explorer.css"
```
Thanks to @casperOne for pointing this out in
https://github.com/microsoft/SandDance/issues/155#issuecomment-568629839

**Comment by danmarshall** [comment]
I will add this to the Readme, thank you for pointing this out

**Comment by t-book** [comment]
@danmarshall yes this did it thanks!
