### ISSUE TITLE
SandDance as docker containers?

### ISSUE THREAD

**Issue by gannebamm** [microsoft/SandDance#192]
Hello,
I thought I have seen a docker composition for SandDance somewhere? Do I remember incorrectly, or is my google-fu bad today?
Shall I use Bing instead 😅

**Comment by danmarshall** [comment]
Hello, I do not recall seeing a Docker for SandDance.

Perhaps you can ask Jeeves 😂
![image](https://user-images.githubusercontent.com/11507384/76557805-6e15a280-6459-11ea-8f16-100afa00b286.png)
 
If you create one, please share it 👍

**Comment by t-book** [comment]
😂😂

@gannebamm @danmarshall Not the prettiest you might have seen so far but good for a quick start: 
- https://github.com/csgis/sanddance-docker/tree/master
- https://hub.docker.com/r/tbook/sanddance-app
