### ISSUE TITLE
Feature request: right-click file in Search pane to "Open to the Side"

### ISSUE THREAD

**Issue by mikehurl** [microsoft/SandDance#197]
As per the title, when I perform a search in the Search pane, I would like to be able to right-click a file in the results section and be provided with the option to open the file to the side. I couldn't find anything to suggest this is already possible with a setting or extension, so apologies if a solution is already provided :blush:

**Comment by danmarshall** [comment]
Hi @mikehurl - that would be pretty handy! But I think you're right, in that this functionality isn't provided by the VSCode extension model. There's no menus for search here: https://code.visualstudio.com/api/references/contribution-points#contributes.menus

**Comment by mikehurl** [comment]
Wrong repo 🤦‍♂
