### ISSUE TITLE
DeckGL upgrade

### ISSUE THREAD

**Issue by mogmog** [microsoft/SandDance#203]
This looks a very interesting project, but for those of us already using Deck version 8, I suspect there will be issues using it in a existing project.

Are there plans to migrate this to Deck 8?

**Comment by danmarshall** [comment]
Hi @mogmog , yes that's on the roadmap. I'm interested to know if the deck.gl canvas can be shared between projects... We have some lifecycle hooks to tap into where layers can be added, but this has yet to be tested. Do you think this is the type of API you might use?

**Comment by mogmog** [comment]
Im not a Deck core developer, cant see why it could not be shared between projects.

What I do know for sure is that, having been working with Deck for a while, it is an incredible framework that seems somewhat misunderstood at the moment, you guys obviously have discovered its power. 

I would certainly use Sand Dance components for filtering and viz in my projects if it was brought up to date. I recommend checking some of the latest deck developments here as there are several that are not available in v 6

https://deck.gl/#/examples/overview?section=core-layers

**Comment by danmarshall** [comment]
This is now code-complete in master. It will be published after some more beta testing.
https://sanddance.js.org/app-3.0.0-beta.1/
