### ISSUE TITLE
Periods in column names prevent proper rendering of charts

### ISSUE THREAD

**Issue by claywagner** [microsoft/SandDance#204]
Hello, I have been using SandDance recently, and I have discovered a bug related to having periods in the column name.

When loading a CSV that has periods in the column name (example below), no chart visualization is provided.
```
"log.cycle_iteration","foo.bar"
1,5
2,6
3,7
4,8
5,2
6,4
```

When loading a similar CSV with replacing the `.` with another separator such as `__`  (example below), the chart is properly shown.
```
"log__cycle_iteration","foo__bar"
1,5
2,6
3,7
4,8
5,2
6,4
```

Obviously I would alter the format of the CSV if I could, but I have received these files from an external vendor. I would like to avoid preprocessing every CSV just to visualize charts.

**Comment by danmarshall** [comment]
would you mind trying to repro this in our new beta version?
https://sanddance.js.org/app-3.0.0-beta.1/

**Comment by claywagner** [comment]
Apologies on the late response.

I am still seeing this bug on both beta 1 and the newer beta 2 branch.
