### ISSUE TITLE
Is there a way to pause the renderer while sanddance is hidden?

### ISSUE THREAD

**Issue by jkelleyrtp** [microsoft/SandDance#210]
I have multiple -gl rendering objects on the page, and need to prevent sanddance from rendering when I'm not using it.

I've found that it's possible to access the presenter from the viewer field on the explorer element, but I'm not sure how I would toggle it off and on as I need.

**Comment by danmarshall** [comment]
Haven't tried to do this, but perhaps you can add an `onStage` handler: `(stage: Stage, deckProps: DeckProps) => void`, which gives you the `deckProps`. You may be able to empty the `views` array property. No View= no view ?

**Comment by jkelleyrtp** [comment]
The rendering overhaul of SandDance is actually dom-related, not deck related. 

For posterity, I advise not using SandDance in a functional component, and instead as a normal React Class Component and aggressively disabling re-render updates.
