### ISSUE TITLE
VS-Code extension: Possibility to pipe-in data?

### ISSUE THREAD

**Issue by oschulz** [microsoft/SandDance#213]
Could there be a way to pipe data into the SandDance VS-Code extension from code (Julia, Python, ...) executed within VS-Code? Or maybe this is already possible?

(CC @davidanthoff)

**Comment by davidanthoff** [comment]
Another way to ask this: is there an API for other VS Code extensions where I can pass some tabular data and then the sanddance webview shows up in VS Code?

**Comment by oschulz** [comment]
For other people following this thread: [SandDance issue 213](https://github.com/microsoft/SandDance/issues/213).

**Comment by danmarshall** [comment]
@oschulz @davidanthoff what is the piping mechanism? Can you direct it to a file? If so, we might be able to add a watcher to the file.

**Comment by davidanthoff** [comment]
I was more thinking about something in-memory?

But I'm also starting to wonder whether we actually would need more something like the [Data Explorer](https://github.com/jupyterlab/jupyterlab-data-explorer) in JupyterLab for this scenario that could act like a "clearing house" for data sets, and then different extensions could hook into that.

**Comment by RandomFractals** [comment]
vscode doesn't have any data piping mechanism or api for extensions to share data.

so, anything you guys want to design for sandance and other extensions to do it would have to be custom.

**Comment by danmarshall** [comment]
Closing this for now, thanks for the discussion.
