### ISSUE TITLE
 Feature request: Image/SVG overlay

### ISSUE THREAD

**Issue by YasharF** [microsoft/SandDance#222]
In some cases, it would be helpful to have an image or vector drawing with some opacity render on the X-Y plane, at the lowest z data point, or at some offset.  An example would be to add an outline of the US States in the Demo Vote example.  Another example would be to load a custom logo or watermark.  Another example would be to load a data point of interest with a different symbol.

I suspect loading such an image would require some parameters for offset and scaling.

A stretch goal for this feature is to import a 3D model for 3D plots.

**Comment by danmarshall** [comment]
We now have a background Image feature, check it out at the bottom of the Chart options:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/11507384/212200965-0ebace39-6175-4b2b-85d2-bb56b628b7f9.png">
