### ISSUE TITLE
example code?

### ISSUE THREAD

**Issue by geohuz** [microsoft/SandDance#227]
Is there any example code to show how react or vanilla usage of sanddance? I didn't find any valuable document about how to make our own data visualization in either way. If there is no narrative document on how does it work, we should at least learning by reading the code, so where is the **demo/example** folder on the github?

**Comment by danmarshall** [comment]
Hi @geohuz first, choose one of these components to see how to get started / install into your project:
* [sanddance](/microsoft/SandDance/tree/master/packages/sanddance/README.md) - the core SandDance visualization canvas.
* [sanddance-react](/microsoft/SandDance/tree/master/packages/sanddance-react/README.md) - the core SandDance visualization canvas for use in React based applications.
* [sanddance-vue](/microsoft/SandDance/tree/master/packages/sanddance-vue/README.md) - the core SandDance visualization canvas for use in Vue based applications.
* [sanddance-explorer](/microsoft/SandDance/tree/master/packages/sanddance-explorer/README.md) - the core SandDance visualization canvas with UI to enable data exploration, for use in React based applications.

Then you can take a look at some examples [here](https://sanddance.js.org/examples/) and view source to see how they work. Also take a look at issue #155 and #121

Other examples in the repo:
* https://github.com/microsoft/SandDance/tree/master/packages/sanddance-test-umd
* https://github.com/microsoft/SandDance/tree/master/packages/sanddance-test-umd

**Comment by danmarshall** [comment]
Related: #182
