### ISSUE TITLE
X axis (or Y depending on chart type) does not generate proper bins (empty bins)

### ISSUE THREAD

**Issue by CoolDixon** [microsoft/SandDance#228]
I have a CSV dataset with 4 class values (2001, 2002, 2003 and 2004) with their respective values  so it naturally should be grupped in 4 unique bins, and within the bins classified by values. The problem is that is creates empty (duplicated) bins
![Screenshot 2020-05-20 at 11 19 31](https://user-images.githubusercontent.com/5981332/82430216-54ae5980-9a8d-11ea-9a0c-6ef0c61e86a2.png)

If I specify 4 bins (or even 5) it groups 2 of them!

![Screenshot 2020-05-20 at 11 31 41](https://user-images.githubusercontent.com/5981332/82430374-89221580-9a8d-11ea-916a-9c78cc40b5f8.png)

**Comment by danmarshall** [comment]
Thanks for the report. Can you see if this repros in our new beta version?
https://sanddance.js.org/app-3.0.0-beta.1/

**Comment by CoolDixon** [comment]
Dear Dan,

It happens too in the beta versión, it is even worst as x axis max bin slider is bigger and it is more difficult to limit to less bins (select 4 in this case) than before

[cid:image001.png@01D62F52.18397210]

I send you attached a copy of the dataset I’m using to test

When is it expected to be released the new version? Is it released at the same time for Azure Data Studio?

Best regards,

Carlos

**Comment by danmarshall** [comment]
I'm unable to repro in our latest version, so closing this for now. Thanks for the report and for providing a data sample for the repro.
