### ISSUE TITLE
Better way to change data in sanddance-explorer

### ISSUE THREAD

**Issue by jkelleyrtp** [microsoft/SandDance#238]
Currently I'm using `.load()` to update data in the chart. This has the unwanted side effect of spinning up a new webgl context every time, and killing my other webgl contexts on the page (oldest ones get killed first). 

I've tried setting state with the datafile and forcing the renderer to render the new data, but neither seem to update the interface.

My data is in the form of:

```
data = [state1, sate2, state3, state4];
```

And right now I'm `loading` `data[0]`, `data[1]`, etc as I want to dive into each state separately from each other.

Any thoughts?

**Comment by jkelleyrtp** [comment]
A little research... I can change the data by reference but need to "kick" sanddance somehow to update it.
Currently, I can change the chart type and the data will update. Is there a better/faster method to "poke" sanddance to render the new data without `load`?

**Comment by danmarshall** [comment]
Hi @jkelleyrtp, you can always use the underlying SandDance.viewer object which is imperative, not reactive. Calling its `render` method will definitely give it a kick.

**Comment by jkelleyrtp** [comment]
Awesome, thanks!
