### ISSUE TITLE
Sanddance Vue Beta2 example

### ISSUE THREAD

**Issue by gavinmckay** [microsoft/SandDance#239]
Hi team,

Congrats on getting a Beta2 released! :) I'm trying to create a Sanddance Vue to test Treemap visualisation, but I can't get the component to display anything at all. I'm using this element:

`<sand-dance-vue :data="sanddancedata.data" :insight="sanddancecfg.insight" />
`
with this Insight configuration:

```
              sanddancecfg: {
                insight: {
                  chart: "treemap",
                  size: {height: 400 , width: 400},
                  columns: {
                    x: "name"
                    ,y: "value"
                  }
                }
              },
```

and this JSON data:

```
[{
		"name": "10Mb to 100Mb",
		"value": 1
	}, {
		"name": "1Mb to 5Mb",
		"value": 15
	}, {
		"name": "0 Kb",
		"value": 71
	}, {
		"name": "100Kb to 1Mb",
		"value": 99
	}, {
		"name": "10Kb to 50Kb",
		"value": 394
	}, {
		"name": "< 10Kb",
		"value": 5572
	}, {
		"name": "0 Kb",
		"value": 16921
	}
]

```
which is assigned to the sanddance-vue component via:

this.sanddancedata.data = sanddancejson;

However my Vue page displays this:

![image](https://user-images.githubusercontent.com/32010376/83971992-47182100-a921-11ea-9795-e7bad05b5c8e.png)

There are no javascript errors on the page so it seems the sanddance-vue component is registered correctly. I have saved JSON separately and can successfully load it into the online Sanddance demo.

Any ideas what I am doing wrong here?

**Comment by danmarshall** [comment]
Hi Gavin, I think you need to add the stylesheet from `@msrvida/sanddance/dist/css`, and set a size for `.sanddance-VueViewer`.

I'm not a Vue expert, but here's a working example:
```
<template>
  <div id="app">
    <SandDanceVue v-bind:data="data" v-bind:insight="insight" />
  </div>
</template>

<script>
import * as deck from "@deck.gl/core";
import * as layers from "@deck.gl/layers";
import * as luma from "@luma.gl/core";
import * as vega from "vega";
import SandDanceVue, { SandDance } from "@msrvida/sanddance-vue";

SandDance.use(vega, deck, layers, luma);

const data = [{ a: 1 }, { a: 2 }, { a: 3 }];

const insight = {
  chart: "barchartV",
  columns: {
    x: "a",
    z: "a"
  },
  size: {
    height: 500,
    width: 500
  },
  view: "3d"
};

export default {
  name: "App",
  components: {
    SandDanceVue
  },
  data: () => {
    return {
      data,
      insight
    };
  }
};
</script>

<style>
.sanddance-VueViewer {
  height: 700px;
  border: 1px solid black;
}
</style>

<style src="@msrvida/sanddance/dist/css/sanddance.css" />
```

If there's a better syntax for templating, please let me know 🤓

Also, you package.json will need these for beta.2:
```
    "@deck.gl/core": "^8.1.9",
    "@deck.gl/layers": "^8.1.9",
    "@luma.gl/core": "^8.1.3",
    "@msrvida/sanddance-vue": "^3.0.0-beta.2",
    "vega": "^5.13.0",
```

These should be added to the [readme](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-vue/README.md)

**Comment by gavinmckay** [comment]
Thanks Dan! I'll try this configuration, I just have to get past this @luma.gl upgrade error:

![image](https://user-images.githubusercontent.com/32010376/84148468-64282d80-aaa2-11ea-8554-a18f8ec2dab7.png)

which looks like some npm fun in the background, then I'll try the configuration above.

**Comment by gavinmckay** [comment]
Hi Dan,

Looks like it is something else, the sample you provided above worked straight away:

![image](https://user-images.githubusercontent.com/32010376/84149116-49a28400-aaa3-11ea-8f42-b23abeaee0da.png)

I'll run some more tests and report back...

**Comment by gavinmckay** [comment]
Fixed - I checked the insights configuration for the [TreemapTest](https://github.com/microsoft/SandDance/blob/master/docs/tests/v3/umd/js/treeMapTest.js) demo and saw I had the columns configuration completely wrong, should be the following for Treemap (for my data):

```
insight: {
            chart: "treemap",
            size: { height: 400, width: 400 },
            **columns: {
              color: 'name',
              size: 'value',
              uid: 'name'
            },**
            scheme: 'category10'
          }

```
 
just got a bit ambitious with the graphing options :)

![image](https://user-images.githubusercontent.com/32010376/84151183-52e12000-aaa6-11ea-969f-073856860678.png)

CSS battles ahead, but looks great to me!
