### ISSUE TITLE
Tooltip flickers

### ISSUE THREAD

**Issue by mariusgessler** [microsoft/SandDance#257]
Hello,
I'd like to say I'm very impressed by the capabilities of Sanddance and really appreciate the possibilities it brings!

Unfortunately, I have an issue with the tooltips when hovering as seen [here](https://imgur.com/a/hnyNB28). They're quite jittery, plus they don't have a black background as the ones in the demo have. Any idea how to solve this?

**Comment by danmarshall** [comment]
Have you added the `sanddance.css` stylesheet to your page? You may want to view-source of this example:
https://sanddance.js.org/tests/v3/umd/test.html

Also see #129

**Comment by mariusgessler** [comment]
That worked, thanks!
