### ISSUE TITLE
Can't open Sanddance, no Data tab in Explorer

### ISSUE THREAD

**Issue by Arthur-Ni** [microsoft/SandDance#266]
The Data tab in Explorer is missing, right click on the open file in the Open Editors tab doesnt show the option to open Sanddance.
Any ideas to fix this?

**Comment by danmarshall** [comment]
Hello, can you add a screenshot of your issue? I'm guessing you mean in VSCode...

**Comment by Arthur-Ni** [comment]
Hi Dan,

You’re correct, I mean VSCode.
According to the video that’s shown when I select the SandDance extension in VSCode, I have to right click on the open file in the Data section of Explorer, and select ‘View in SandDance’.
As you can see from the screenshot below, I don’t have that Data section, and right clicking on the file in the Open Editors section doesn’t give me the option to view in SandDance.


[cid:image002.png@01D66BD3.F0351350]

Any help would be welcome.

Best regards,
Arthur

**Comment by Arthur-Ni** [comment]
Hi Dan,
I found out I can invoke SandDance by right clicking on the tab label instead of on the file name, so everythings works now.
Great extension, thanks for the good work!
Best regards,
Arthur
