### ISSUE TITLE
Manually setting categorical variables

### ISSUE THREAD

**Issue by Poshi** [microsoft/SandDance#270]
I have a dataset that contains some column which is just an ID represented as an integer. I'd like to treat this column as a categorical one, but it is automatically classified as a quantitative one.
Unfortunately, I cannot find any way to tell SandDance to consider that column as categorical. It would be a nice addition to add a way to make this kind of adjustments. And if there exists a way... giving it greater relevance/visibility would be good, as I didn't found it despite having look through the whole interface for it.

**Comment by danmarshall** [comment]
Hi @poshi, that would be a good feature to add. Are you using the GUI or do you mean programmatically?

**Comment by Poshi** [comment]
I was using the GUI, trying some EDA. But programmatically would be good too, obviously. In fact, programatically would be somethig easier to handle, as you already have your data in a know structure that you can modify easily before feeding it to SandDance. But when you are in the GUI... there's no out.

**Comment by nik0sc** [comment]
Actually @lleeoo's first option is better as it would be in sanddance-explorer and other apps embedding it would get the feature too. There's a `distinctValueCount` property in `ColumnStats` which could support such a feature.

So the `Settings` component would examine all numeric columns' distinctValueCount and if less than the current threshold, set the column to non-quantitative.

**Comment by nik0sc** [comment]
If nobody else is taking this then I'd like to try implementing it. So far I've managed to add a very basic toggle in the Data Browser pane for numeric columns. @danmarshall do you have any ideas or preferences about this?

**Comment by danmarshall** [comment]
@nik0sc thanks for the offer! Would you mind attaching a sketch of the UI of your proposal?

**Comment by nik0sc** [comment]
@danmarshall I'm thinking of a pop up dialog where the user can choose the quantitative/categorical type for each numeric column
![Capture2](https://user-images.githubusercontent.com/24191562/185665375-b58df5bf-0447-4a76-a63f-9fadfec0c5b2.png)

**Comment by danmarshall** [comment]
@nik0sc looks good! Can you ensure there's an 'undo' ability?
