### ISSUE TITLE
Vega-deck.gl demos fail to render charts

### ISSUE THREAD

**Issue by tjweedle** [microsoft/SandDance#271]
This seems to impact all of the demos on [sanddance.js.org](https://sanddance.js.org/examples/):
- [simple vega spec](https://sanddance.js.org/tests/v3/umd/vega-deck.gl.test.html)
- [transition between vega specs](https://sanddance.js.org/tests/v3/umd/transition.html)
- [cubeTest](https://sanddance.js.org/tests/v3/umd/cubeTest.html)

The console includes two errors:
```
dist.min.js:11 deck: error during initialization of TextLayer({id: 'LAYER_TEXT'}) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.assign.getFontWidth (dist.min.js:1)
    at e.value (dist.min.js:1)
    ...
    at e.value (dist.min.js:11)
    ...
dist.min.js:1 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.assign.getFontWidth (dist.min.js:1)
    at e.value (dist.min.js:1)
    ...
```

The page loads, but no graph is displayed:
![image](https://user-images.githubusercontent.com/70910658/92408044-34b0ad80-f0f1-11ea-9879-e515eded8c48.png)

### Platform
**Windows 10, Chrome 84.0.4147.135**

**Comment by danmarshall** [comment]
Looks fixed now, thank for the report.
