### ISSUE TITLE
Axes values with non-English characters in PowerBI visual

### ISSUE THREAD

**Issue by doubleamp** [microsoft/SandDance#273]
Hello. I am having problems displaying non-English characters in the axis values with the PowerBI visual. Is there anything that can be done? Reading issues #78 or #127 it seems that there is a work around when working with the source code, but I do not think that I can do anything with the visual that I get from the PowerBI app source...

**Comment by danmarshall** [comment]
Hello, it may be that those PR's weren't part of the PowerBI release. We will get a new release out, but FYI the process takes a couple of weeks.

**Comment by doubleamp** [comment]
OK, perfect. I will wait for the new release. Thanks a lot.
