### ISSUE TITLE
Default settings for the PowerBI Visual

### ISSUE THREAD

**Issue by doubleamp** [microsoft/SandDance#274]
Hello again.
Is there any way to change the default settings value in the PowerBI Visual? That is, instead of the default for 'Text scale' being '2', having it set by default to '1.8'. Alternatively, if the settings could be made permanent (once set, they would not refresh unless changed again), that would also work.
Thanks in advance.

**Comment by danmarshall** [comment]
Hello, there's no API for us to persist user preferences in Power BI.
As for the text size, other users have noted that it is somewhat large, see #468
