### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by yankolo** [microsoft/SandDance#278]
I am currently trying to debug the project. To debug I am running "npm start" and setting up a Javascript debugger as per the instructions found in the documentation (I am using Webstorm IDE, I believe VS Code is similar). However, none of my breakpoints are being hit. 

I am not sure exactly how to make debugging work. I believe the debugger is not working because this is a monorepo using Lerna. Perhaps, there is a problem with the source maps generation?

Can someone lend me a hand with this issue? Do I need to add any additional options to Lerna? Or perhaps TypeScript needs to be configured?

**Comment by danmarshall** [comment]
Hello, and thanks for debugging the project! I currently do not have source maps set up, so all debugging is done in the browser itself, which has not been too bad. Let me know if you have any ideas how to set up source maps.

**Comment by yankolo** [comment]
Thank you for your response. I see. I don't mind to debug from the browser as I don't have any idea on how to setup source maps for the project at the moment. 

Do you mind telling me how you are debugging with the browser? I am trying to debug the file "SandDance\packages\sanddance-explorer\src\explorer.tsx", though I don't know if it is possible to debug TypeScript files through the browser.

**Comment by danmarshall** [comment]
I look for a line of code in the output. Remembering that some TypeScript declarations like interfaces do not appear in JavaScript. So for example of explorer.tsx, I would search for this line:
https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/src/explorer.tsx#L129

The first appearance of `dataBrowserZeroMessages` is at line of 21763 of [sanddance-app,js](https://sanddance.js.org/app/js/sanddance-app.js). Hopefully this makes sense. Yes, source maps would make this process easier ;)

**Comment by yankolo** [comment]
Alright, thank you for the explanation, it makes sense. I will try it out.

**Comment by danmarshall** [comment]
Related: #182
