### ISSUE TITLE
TypeError: Cannot read property 'Component' of null in SandDanceReact 

### ISSUE THREAD

**Issue by bengraves-five** [microsoft/SandDance#285]
Hi, I am trying to use the `@msrvida/sanddance-react` package to add a sanddance to my typescript react app. However I am getting for following error when the component renders:

```
TypeError: Cannot read property 'Component' of null
    at _SandDanceReact (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:274897:85)
    at renderWithHooks (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:506201:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:508880:13)
    at beginWork (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:509994:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:491586:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:491635:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:491690:31)
    at beginWork$1 (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:514601:7)
    at performUnitOfWork (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:513552:12)
    at workLoopSync (http://localhost:6006/vendors~main.c92b952e17da10f04009.bundle.js:513528:22)
```

 I have the following code:

Graph.tsx:

```
import React from "react";
import { SandDanceReact, SandDance } from "@msrvida/sanddance-react";

import * as deck from "@deck.gl/core";
import * as layers from "@deck.gl/layers";
import * as luma from "@luma.gl/core";
import * as vega from "vega";

SandDance.use(vega, deck, layers, luma);

export function Graph() {
  return (
    <SandDanceReact
      data={[
        { a: 1, b: 1 },
        { a: 2, b: 2 },
        { a: 3, b: 3 },
      ]}
      insight={{
        chart: "barchartV",
        columns: {
          x: "a",
          color: "b",
        },
        scheme: "reds",
        size: {
          height: 600,
          width: 800,
        },
      }}
    />
  );
}
```

Package.json:

```
dependencies: {
    ...
    "@deck.gl/core": "^8.1.5",
    "@deck.gl/layers": "^8.1.5",
    "@msrvida/sanddance-react": "^3",
    "@luma.gl/core": "^8.1.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "vega": "^5.11",
    ...
}
```

If anyone could help me out with debugging this it would be very much appreciated, thanks!

**Comment by danmarshall** [comment]
Hello, thanks for posting this issue. Looks like you found a bug in our documentation 🙃. Can you also import the `use` function, and pass your `React` and `ReactDOM` - see https://github.com/microsoft/SandDance/blob/master/packages/sanddance-react/src/base.ts

**Comment by bengraves-five** [comment]
Thanks for this, so I added

```
import * as React from "react";
import * as ReactDOM from "react-dom";

SandDance.use(React, ReactDOM, vega, deck, layers, luma);
```

However I get feedback in my IDE that the `use` function only expects 4 arguments (vega, deck, layers, luma)

![Screenshot 2020-11-23 at 17 25 27](https://user-images.githubusercontent.com/68950912/99994438-e7b7ab80-2db0-11eb-9edc-22154fa4fe33.png)

And still the same error `TypeError: Cannot read property 'Component' of null in SandDanceReact` when I try to render it.

**Comment by danmarshall** [comment]
try:
```
import { SandDanceReact, use } from "@msrvida/sanddance-react";
```
then invoke `use` instead of `SandDance.use`

**Comment by bengraves-five** [comment]
Ah yes that worked, thank you. So I have this rendered now? Seems like the actual chart is missing? The canvas that is rendered is just blank:

![Screenshot 2020-11-24 at 09 15 36](https://user-images.githubusercontent.com/68950912/100073646-addcb880-2e35-11eb-8d01-a484e1757dd6.png)

Here is the code:

```
<SandDanceReact
      data={[
        { a: 1, b: 1 },
        { a: 2, b: 2 },
        { a: 3, b: 3 },
      ]}
      insight={{
        chart: "barchartV",
        columns: {
          x: "a",
          color: "b",
        },
        scheme: "reds",
        size: {
          height: 600,
          width: 800,
        },
      }}
    />
```

**Comment by danmarshall** [comment]
I think now is a matter of CSS styling.
Can you import the default style sheet:
```js
import "@msrvida/sanddance-react/dist/css/sanddance-react.css"
```
Thanks for your patience. You also may want to specify your canvas size by overriding this css.

**Comment by bengraves-five** [comment]
Okay, now I just have a big empty screen with a wide box at the top right? 

Canvas size seems to be 100% of the width and 200px in height

![Screenshot 2020-11-24 at 15 53 46](https://user-images.githubusercontent.com/68950912/100118028-55291200-2e6d-11eb-818e-485530ff74c4.png)

**Comment by danmarshall** [comment]
can you share your repo?

**Comment by danmarshall** [comment]
Hi @bengraves-five , if this continues to be an issue for you please re-open. I'm closing this issue for now, thanks.
