### ISSUE TITLE
3D Navigation in 2019 Version

### ISSUE THREAD

**Issue by kjbay** [microsoft/SandDance#286]
I've created a 3D scatter plot and am looking for a good way to navigate around the chart. Previous version looks to have had more flexibility around this. Am I missing something?

**Comment by danmarshall** [comment]
Hello, are you referring to using the mouse to orbit the view ?

**Comment by kjbay** [comment]
I am, maybe that's the issue I'm seeing? Only using the trackpad. Mouse recommended?
Thanks for your feedback.

**Comment by danmarshall** [comment]
I use the trackpad on my Microsoft surface. What platform are you using, and can you describe the tracking issue?

**Comment by kjbay** [comment]
Yes, when the hand is clicked and held down - if I try to then move around I would expect it to rotate 360 degrees so I can see any view, however it just moves the window up/down left/right

**Comment by danmarshall** [comment]
You can use shift-click-hold-move to orbit. Sorry this wasn’t apparent, we should have some UI that gives these hints.

**Comment by kjbay** [comment]
Exactly what I needed. Thanks for your help!
