### ISSUE TITLE
PBI visual - Clause disabled

### ISSUE THREAD

**Issue by presense** [microsoft/SandDance#288]
Clause drop downs are disabled in the Power BI visual. Any pointers to why this might be would be useful. The ability to choose between 'and' or 'or' is particularly important.
Thanks
![sanddance clause](https://user-images.githubusercontent.com/3250711/101127533-e0ff2300-3651-11eb-8ce9-689ca59845b2.png)

**Comment by danmarshall** [comment]
Hello, the `and`/`or` mode gets locked in once you have more than 2 clauses. If you want to mix `and`/`or` you can create a new clause group:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/11507384/217660348-26eee237-deff-4e0e-969f-6179e1e3825a.png">
