### ISSUE TITLE
SandDance Explorer snapshot sharing

### ISSUE THREAD

**Issue by nlafleur** [microsoft/SandDance#291]
How to make my SandDance Explorer snapshots shareable?

In the SandDance Explorer example [https://sanddance.js.org/app](https://sanddance.js.org/app) it is possible to share your snapshot with the 'share' button;
![image](https://user-images.githubusercontent.com/40174298/102886945-56dafb00-4456-11eb-9330-2518b0a9b35f.png)

I can't find any information about this share/export option in the docs, the only 2 things I could find;

A function called SnapshotExport - https://github.com/microsoft/SandDance/blob/b0725a2eb975b248d6e6a61a2471d0fa97f41669/packages/sanddance-app/src/snapshots.tsx#L269

And a button that changes the url which makes it shareable - https://github.com/microsoft/SandDance/blob/b0725a2eb975b248d6e6a61a2471d0fa97f41669/packages/sanddance-app/src/snapshots.tsx#L301-L316

^These look like the function and button that I'm looking for but I don't know how to implement this in my code

Example of my explorerProps:

```
return {
  //logoClickUrl: '/',
  mounted: explorer => {
    const service = this.getServices(process.env.webserver);
    const url = myUrl
    const dataFile = {
      displayName: 'Mangrove',
      dataUrl: url,
      type: fileType
    }
    explorer.load(dataFile);
  },
  compactUI: { compactUI },
  dataExportHandler: true
}
```

I was expecting that there would be an option like; 'snapshotSharing: boolean'.

---

**DataExport:**
In my code example above you can see that I've set the 'dataExportHandler' on true, but whenever I try to export my rows like this:
![image](https://user-images.githubusercontent.com/40174298/102890979-b4267a80-445d-11eb-81c9-f0f66c66fd94.png)
It displays the following error in my console; `Uncaught TypeError: this.props.dataExportHandler is not a function`

Just like the snapshot sharing I cannot find anything regarding this function in the docs.

**Comment by danmarshall** [comment]
For snapshot sharing, see [snapshotProps](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/src/explorer.tsx#L77), an object with a [getActions](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/src/dialogs/snapshots.tsx#L18) property, which returns an array of your own `SnapShotActions](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/src/interfaces.ts#L33). Here you can provide your own React elements for the snapshot actions.

The `dataExportHandler` prop should be a function, please see [this example](https://github.com/microsoft/SandDance/blob/9d416d36e6f0fb827ec76cd492e7cef753158a2e/packages/sanddance-app/src/sanddanceApp.tsx#L351)

**Comment by danmarshall** [comment]
Closing this for now, if you have any feedback, please feel free to re-open.
