### ISSUE TITLE
Unable to get axis labels and titles to render correctly

### ISSUE THREAD

**Issue by nkerr** [microsoft/SandDance#293]
I have created an Angular 2 project to use the SandDance explorer widget but the axis titles and label fonts do not render correctly.
I then tried creating a React app, following [your instructions](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/README.md) and it had the exact same issue.

Is there something wrong with the latest (vega/deck) dependencies that may be causing the issue?

![image](https://user-images.githubusercontent.com/791075/103022942-f5309480-451a-11eb-95fd-49921022054d.png)

**Comment by danmarshall** [comment]
I believe #283 should fix this

**Comment by nkerr** [comment]
Thanks @danmarshall,

When do you expect to release an official version that includes the fix?

Also, is it possible to use SandDance-Explorer in a simple JavaScript application, without using React, Vue or other frameworks?

**Comment by danmarshall** [comment]
[Version 3.1.1](https://www.npmjs.com/package/@msrvida/sanddance/v/3.1.1) contains the fix and was published 5 days ago 😀

As for the Explorer,  it has quite a lot of UI componentry, and statefulness. For this reason it was built with React. You may also try embedding it as an iframe. I don't have a write-up for this, but you can see it in action in our [Observable page](https://observablehq.com/@danmarshall/sanddance-explorer).

**Comment by nkerr** [comment]
Excellent. Thanks @danmarshall  !

**Comment by nitrousdigital** [comment]
The fonts work perfectly now.
Thanks @danmarshall !!
![image](https://user-images.githubusercontent.com/506984/104396767-4e3b8900-5519-11eb-8f14-ee842f71b510.png)

**Comment by danmarshall** [comment]
Great! Thanks!
