### ISSUE TITLE
Retain chart settings across data load operations?

### ISSUE THREAD

**Issue by nkerr** [microsoft/SandDance#299]
Please could you let me know, is it possible to retain SandDance Explorer chart settings across load operations?
I would like to be able to update/replace the loaded data set but retain as many of the selected SandDance Explorer options as possible.
What is the best way to achieve this?

Thanks in advance for any info you are able to provide.
Nick

**Comment by danmarshall** [comment]
Hello, can you tell me which component you are using? You can get the current `insight` object and re-apply it.

**Comment by nkerr** [comment]
Thanks @danmarshall,

I'm using the SandDance Explorer component.

**Comment by danmarshall** [comment]
So, with your explorer object, you can call `explorer.getInsight()` to get the current insight. Then when you load your new data, you can call `explorer.load(data, ()=>insight)`.

**Comment by nkerr** [comment]
Excellent. Thanks @danmarshall 
I'll give that a try.

**Comment by nkerr** [comment]
That worked perfectly. Thanks again @danmarshall

**Comment by danmarshall** [comment]
@nkerr great!!
