### ISSUE TITLE
Sandance doesn’t react well to lack of horizontal space.

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/SandDance#3]
Area: Azure Data Studio extension
Issue:
Sandance doesn’t react well to lack of horizontal space.
Just use split view to see issues
 
![image](https://user-images.githubusercontent.com/10819925/56236385-531a9280-603e-11e9-8fe0-9047098a4b38.png)

**Comment by danmarshall** [comment]
One thing you can do is collapse the left pane: 
![image](https://user-images.githubusercontent.com/11507384/56251513-bfaa8700-6068-11e9-8db8-6dccc923334b.png)

Other than that, perhaps we can add a slider which lets you control the aspect ratio...

**Comment by danmarshall** [comment]
Viewport now clips when ticks are smaller than 20 pixels.
