### ISSUE TITLE
Custom groupings in drop-downs

### ISSUE THREAD

**Issue by nkerr** [microsoft/SandDance#300]
Is it possible for the SandDance Explorer chart drop-down menus to group attributes using custom groups?
Currently, the various chart configuration drop-downs group attributes into 'Numeric' or 'Categorical' groups.

Since I have a data set with a potentially large number of attributes, it would be helpful if I could define my own groups to better organize the attributes in the drop-down.

If this is not currently possible, please could you consider adding this feature in a future release?

Thanks!
Nick

![image](https://user-images.githubusercontent.com/791075/104866236-0b5c2580-590c-11eb-8427-90d0db7f44f5.png)

**Comment by danmarshall** [comment]
The code for grouping these is [here](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/src/controls/columnMap.tsx#L136), you may want to take a look. It may be easy to pass in a custom function via props.

**Comment by nkerr** [comment]
Thanks @danmarshall

**Comment by danmarshall** [comment]
Closing this for now, not sure if there is a general-purpose solution. Depending on your usage context, you may be able to solve it programmatically.
