### ISSUE TITLE
Styling not included when spinning up example app

### ISSUE THREAD

**Issue by johanbook** [microsoft/SandDance#305]
I tried spinning up the example in https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/README.md using a Create-React-App template, but all styling seems to be missing. Have missed something or is the supplied example incomplete?

**Comment by johanbook** [comment]
I tried importing the following css `import "@msrvida/sanddance-explorer/dist/css/sanddance-explorer.css"` which improved it significantly better, but still not as expected, see screenshot.

![2021-02-01-112742_1920x1080_scrot](https://user-images.githubusercontent.com/13253042/106446841-086f4200-6481-11eb-8e19-f523c74d3bcf.png)

**Comment by Buroni** [comment]
I think this is a CSS issue caused by the explorer not having a set height. Giving the explorer component a specific height seems to fix it. 

```css
.sanddance-explorer {
    height: 1000px;
}
```

**Comment by johanbook** [comment]
That fixed it, thanks @Buroni! It would be great if this info could be added to the docs as it seems it is needed to get the app to render properly

**Comment by danmarshall** [comment]
Thanks @Buroni 🥇 
@johanbook - we didn't make any assumptions on how consumers will their component. We are open for pull requests, if you'd like to add this info the readme :)

**Comment by Buroni** [comment]
@danmarshall It may be worthwhile to give `.sandance-explorer` `height: 100%` by default, so that it takes up the height of whatever container a user puts it in rather than collapsing to the height of the legend. This would be expected default behaviour in my opinion. I'm happy to submit a PR.

**Comment by danmarshall** [comment]
Thanks @Buroni - PRs appreciated :)
