### ISSUE TITLE
Incorrect Bar Chart X axis position

### ISSUE THREAD

**Issue by gmalafsky** [microsoft/SandDance#307]
As seen in the quantitative bar chart example at https://microsoft.github.io/SandDance/tests/v3/umd/quanBarChartTest.html the final bar is at an incorrect x tick value. Should be x=3 and is at x=2.5.  This occurred with my data project as well. I did track down through the labyrinth of framework calls to the Vega/Deck libs the method calculating the ticks which is based on coloring (e.g. array of 10 colors made without regard for actual data placement) not the usual charting approach of placing data points and extending x and y axes to ensure data fit within ranges. I did not see an easy way to adjust this and did not want to customize the Vega/Deck code. But, it is a basic principle of charting to get bars positioned correctly.

**Comment by danmarshall** [comment]
This was just fixed in #341 - thanks!
