### ISSUE TITLE
Set initial partial insights to explorer

### ISSUE THREAD

**Issue by kepejas** [microsoft/SandDance#314]
Hi, is there a way to pass only partial insights to initial Explorer load?
For instance, want to use 'blues' scheme on all of my charts, but I want to keep the rest default insights for columns and other stuff as I am not fully aware of what kind I am going to load.

I am using explorer and loading data the same way as [here](https://sanddance.js.org/docs/sanddance-explorer/v3/).

Thanks

**Comment by danmarshall** [comment]
Hello, I think there's a couple of options.

First, when calling `explorer.load(data, getPartialInsight?: (columns: Column[]) => Partial<Insight>)`, you can use the 2nd parameter to return a partial insight. https://sanddance.js.org/docs/sanddance-explorer/v3/api/explorer_class.html#explorer_class

Secondly, you can add `viewerOptions` to your `explorerProps`. [ViewerOptions](https://sanddance.js.org/docs/sanddance/v2/api/types.html#vieweroptions) has an onVegaSpec handler, which will pass you the Vega spec. You can mutate the spec in place, it will then be used for rendering. 
In your case, you can then find the scale used for color, and change its `scheme`.

**Comment by kepejas** [comment]
Thanks a lot for your reply.

The first option doesn't work when passing partial insight, it just loads indefinitely:
```
explorer.load(data, () => ({
   scheme: 'blues'
})

```

The second option does not look as elegant as the first one, but works perfectly. 

Thanks!
