### ISSUE TITLE
Cannot view a CSV file in Azure Data Studio

### ISSUE THREAD

**Issue by elazdins** [microsoft/SandDance#32]
Whenever I try to open a folder in Azure Data Studio (File -> Open Folder), the application restarts.
As soon as I disable the plugin, I can open a folder just fine.

I am using Azure Data Studio version 1.7.0 and SandDance for Azure Data Studio version 1.0.0

Edgars

**Comment by danmarshall** [comment]
Hi Edgars, thank you for reporting this. Can you provide more detail? I am unable to repro.

**Comment by elazdins** [comment]
Sure! What additional information can I provide? The above restarts are happening every single time I attempt to open a folder while the plugin is enabled. As soon as the plugin is disabled restarts no longer happen.

Also - after enabling the plugin I was not able to find any SandDance commands in the command prompt, not sure if they should have appeared there? I also tried right clicking on a CSV file already open in Azure Data Studio, but did not see any "View in SandDance" option available.

Thank you,

Edgars

**Comment by danmarshall** [comment]
Hi Edgars, when you say "enabled" do you mean from the Extensions sidebar?
![image](https://user-images.githubusercontent.com/11507384/57593595-04530200-74f1-11e9-8aff-7bea2fbe2eab.png)

Or do you mean when you are actually looking at a SandDance chart in a tab?

If it's the former, I'm not sure if there is any SandDance code loaded at all. Can you provide a complete set of steps to repro?

**Comment by elazdins** [comment]
Hi Dan,

It appears you are correct - the Open Folder functionality does not appear to be working well for me even with the SandDance plugin uninstalled (could be issue https://github.com/microsoft/azuredatastudio/issues/2801)

This leaves me with a problem though - how can I test out the plugin, if I cannot open a folder? I tried opening a CSV file in Azure Data Studio (which works OK), but there are no SandDance options when I right click on the file or open Command Pallette. 

Reproduction steps:
1) Make sure the SandDance plugin is installed and enabled
![image](https://user-images.githubusercontent.com/4355407/57598507-30579d00-755c-11e9-9fb2-9fd82555c620.png)
2) Go to File -> Open File, select a CSV file.
3) Try to right click on the file, no SandDance option is available
![image](https://user-images.githubusercontent.com/4355407/57598590-7c0a4680-755c-11e9-8ac5-4e82dfd7d534.png)
4) Search in Command Palette, no SandDance option is available 
![image](https://user-images.githubusercontent.com/4355407/57598622-93493400-755c-11e9-8e17-e24e6e7c7620.png)

Technical details:
![image](https://user-images.githubusercontent.com/4355407/57598703-e7541880-755c-11e9-910f-80a6a2978482.png)

Thank you,

Edgars

**Comment by danmarshall** [comment]
Hi Edgars, I am going to close this issue since we have #33 to track the new feature request. Thanks!

**Comment by danmarshall** [comment]
Actually, I see this is different. re-opening.
