### ISSUE TITLE
Azure Data Studio: view PostgresSQL results

### ISSUE THREAD

**Issue by elazdins** [microsoft/SandDance#33]
Hi,

I would like to have the ability to directly view query results in SandDance without having to save them to a CSV file first.

Thank you,

Edgars

**Comment by danmarshall** [comment]
This is now available!
https://cloudblogs.microsoft.com/sqlserver/2019/08/15/the-august-release-of-azure-data-studio-is-now-available/

**Comment by elazdins** [comment]
Hi Dan,

Thank you for the update - how can I view the query results in SandDance without converting to CSV in the new version?

Edgars

**Comment by danmarshall** [comment]
In Azure Data Studio:
* update the SandDance extension 
* Connect to SQL Server instance
* Run a query
* Click the visualizer button in the results grid.

See the link in my previous comment for details.

**Comment by elazdins** [comment]
Thank you Dan for the clarification. I have updated both Azure data studio and the Sanddance plugin. I see the Visualizer button, but when I click on it nothing happens.

If it helps I am attempting to click the Visualizer button after running a PgSQL query that returns a few rows of results. I have looked at all the Log views available from the UI and do not see any messages related to me clicking the button.

Thank you,

Edgars

**Comment by danmarshall** [comment]
I filed an issue with Azure Data Studio, though I am not yet sure if it is their issue, or an issue with either this or the PostgreSQL extension.

https://github.com/microsoft/azuredatastudio/issues/7041

**Comment by elazdins** [comment]
Thank you, Dan! :)

**Comment by Oleg26Dev** [comment]
> I filed an issue with Azure Data Studio, though I am not yet sure if it is their issue, or an issue with either this or the PostgreSQL extension.
> 
> [microsoft/azuredatastudio#7041](https://github.com/microsoft/azuredatastudio/issues/7041)

Btw, I have tried to run Visualizer on SQL Server and PostgreSQL queries results. It does not work.

**Comment by danmarshall** [comment]
@Oleg26Dev Was the SandDance extension installed when you clicked the chart icon?

**Comment by Oleg26Dev** [comment]
I have the latest Azure Data Studio v1.12.2 and the latest SandDance Extension v1.3.9 installed

**Comment by danmarshall** [comment]
@Oleg26Dev Does the **Visualize** icon work for you? Here is a gif showing how it works for me, using a SQL Server query:
![SandDance-azdata-animation4-1400x1024](https://user-images.githubusercontent.com/11507384/67149143-8859a480-f25c-11e9-8fe0-779400262ebc.gif)

Perhaps you can provide a screenshot or gif?

**Comment by Oleg26Dev** [comment]
@danmarshall SQL Server query does not work on my machine, I will check yet once on other machine to be sure.
Could you please try if SandDance works for a PostgreSQL query?

**Comment by danmarshall** [comment]
It currently is not working for PostgresSQL, that is why this issue is open.

**Comment by Oleg26Dev** [comment]
I have checked on other machine. The SQL Server Query works fine on other machine, ok. Probably the 1st machine has problem with Video Card.

**Comment by danmarshall** [comment]
Thanks @Oleg26Dev - we should probably add a check for WebGL and degrade more gracefully.

**Comment by danmarshall** [comment]
Closed via https://github.com/microsoft/azuredatastudio-postgresql/issues/171
