### ISSUE TITLE
Very simple feature request - Save filtered values to csv

### ISSUE THREAD

**Issue by D-Niermann** [microsoft/SandDance#36]
Your tool is very helpful to quickly filter out special points of .csv files, however there is no option to do something with the filtered values outside of SandDance. It would be nice if fitlered values could be saved as a new .csv file. Or at least just open the filtered subset in a new tab as csv, than the user can do whatever he wants with it.

**Comment by danmarshall** [comment]
Thanks for the feature request. This is now live at https://sanddance.js.org/app/

find the export button at the bottom of the Data Browser tab:
![image](https://user-images.githubusercontent.com/11507384/66964361-2f56fa00-f02b-11e9-8421-b6745b212a37.png)
