### ISSUE TITLE
GET https://unpkg.com/deck.gl@8.5.8/deckgl.min.js net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by sdmcallister** [microsoft/SandDance#375]
The test below fails with msg: `GET https://unpkg.com/deck.gl@8.5.8/deckgl.min.js net::ERR_ABORTED 404`

https://github.com/microsoft/SandDance/blob/master/packages/sanddance-embed/test/sanddance-embed.html

**Comment by danmarshall** [comment]
I saw that too, I have a fix ready in the [parcel2 branch, currently in PR](https://github.com/microsoft/SandDance/pull/374)
