### ISSUE TITLE
[Question] - Vega + Deck.gl hello world

### ISSUE THREAD

**Issue by ricardoekm** [microsoft/SandDance#381]
I'm playing with the Vega + Deck.gl submodule, however the basic setup didn't work for me. The code can be found here [codepen](https://codepen.io/ricardoekm/pen/rNwoeeW)

The spec was copied from the Vega tutorial: [let's make a bar chart](https://vega.github.io/vega/tutorials/bar-chart/). The vis div wrapper seems to be initialized but nothing is rendered. No console error is printed.

<img width="989" alt="vega_deck" src="https://user-images.githubusercontent.com/747894/134981931-7d8c5b2d-f0bd-4f80-b8ae-3d048fc150c8.png">

Any help is appreciated, thanks.

PS. If this isn't the correct place to post questions please let me know.

**Comment by danmarshall** [comment]
Hello, thanks for posting the issue  - this is a good place to do that. I modified your example, I needed to change the version and filename for deck.gl to:
```
  <script src="https://unpkg.com/deck.gl@~8.3.7/dist.min.js"></script>
```
After that it rendered! Please let us know where to fix the erroneous code sample. Or better yet, send a PR if possible. Appreciate you reporting this bug!

**Comment by ricardoekm** [comment]
Thanks for the quick reply, it worked!

Just submitted a doc [PR](https://github.com/microsoft/SandDance/pull/382)

**Comment by danmarshall** [comment]
Thanks for the PR 👍🏽
