### ISSUE TITLE
SandDance Explorer Dark Mode

### ISSUE THREAD

**Issue by praveen5959** [microsoft/SandDance#385]
On the Demo page I can see that there is Dark Mode but when I spin up sample React application of SandDance Explorer package there is no theme change button.
![image](https://user-images.githubusercontent.com/30530587/141487653-7a3f6811-175b-43a4-9007-7ada24d0081a.png)

Any idea why this feature is not enabled for me?

**Comment by danmarshall** [comment]
Hello @praveen5959 , the rationale is that sanddance-explorer is a component that can be embedded within any app or page, and we can't assume that the container has theming, or already has its own theme mechanism. So you must access it programmatically. See:
https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/src/themes.ts
https://github.com/microsoft/SandDance/blob/master/packages/sanddance-app/src/sanddanceApp.tsx#L217

**Comment by amcdnl** [comment]
This is probably semi-related - https://github.com/microsoft/SandDance/issues/392
