### ISSUE TITLE
[Feature request] Unlimited categorical color map

### ISSUE THREAD

**Issue by justinchuby** [microsoft/SandDance#390]
Currently if a categorical series has too many categories, SandDance will assign the same color to many of the values. It would be nice if it can _rotationally assign_ colors from the palette, or create a _dynamic palette_ that assigns colors from a continuous spectrum to categorical values.

**Comment by danmarshall** [comment]
Hi @justinchuby , thanks for the idea. If you're using the [SandDance web app](https://microsoft.github.io/SandDance/app/), you can open the JavaScript console and modify the data column metadata to simulate this:

```js
SandDanceApp.explorer.state.dataContent.columns[4].type = 'number'
```

(although this might have other side effects)

Here's a snapshot of the Titanic data with a coninuous color scheme: https://microsoft.github.io/SandDance/app/#{%22title%22:%22Titanic%20barchartV%22,%22description%22:%22%22,%22insight%22:{%22colorBin%22:%22quantize%22,%22columns%22:{%22uid%22:%22Name%22,%22x%22:%22Gender%22,%22y%22:%22Joined%22,%22color%22:%22Job%22,%22z%22:%22TicketCost%22,%22sort%22:%22Survived%22},%22directColor%22:false,%22facetStyle%22:%22wrap%22,%22filter%22:null,%22hideAxes%22:false,%22hideLegend%22:false,%22scheme%22:%22magma%22,%22signalValues%22:{%22RoleZ_ProportionSignal%22:0.6,%22Text_ScaleSignal%22:1.2,%22Text_AngleXSignal%22:30,%22Text_AngleYSignal%22:0,%22Mark_OpacitySignal%22:1,%22RoleColor_BinCountSignal%22:7,%22RoleColor_ReverseSignal%22:false},%22totalStyle%22:null,%22transform%22:null,%22chart%22:%22barchartV%22,%22view%22:%222d%22},%22dataSource%22:{%22dataSourceType%22:%22sample%22,%22id%22:%22titanic%22,%22displayName%22:%22Titanic%22,%22dataUrl%22:%22https://microsoft.github.io/SandDance/sample-data/titanicmaster.tsv%22,%22type%22:%22tsv%22,%22snapshotsUrl%22:null}}

Try hacking the url, for example change `magma` to `blues`.

FYI, we use [Vega's color schemes](https://vega.github.io/vega/docs/schemes/). 

I'd like to hear if others may find this useful. Here's the code section which may need to be re-worked to allow this:
https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/src/palettes/index.tsx#L32-L46

Also, note that it may be simpler for you to do your *rotational assignment* as a new derived column before bringing it into SandDance.

**Comment by danmarshall** [comment]
You might want to try [direct color](https://github.com/microsoft/SandDance/issues/523#issuecomment-1370457077) by adding a color column to your data.
