### ISSUE TITLE
Building sanddance-explorer package

### ISSUE THREAD

**Issue by praveen5959** [microsoft/SandDance#391]
Hi Team,

I am trying to build sanddance-explorer package. Since this is a monorepo. I ran following commands:

`npm install`
and
`npm run build`

I am getting following error during build command:
![image](https://user-images.githubusercontent.com/30530587/148503941-fe8306a2-c37b-4aa8-b2e9-063b882b0390.png)

1.  Can I build only sanddance-explorer package rather than all other packages.?
2.  How to run the sanddance-explore package?

**Comment by danmarshall** [comment]
Hi @praveen5959 , we recently made a change which requires npm version 7 or above, to install peer dependencies. This looks like it might be related to that. Can you check your version of npm, update if possible and try again?

**Comment by praveen5959** [comment]
I am using node@14.17.5 and npm@4.14.14.

**Comment by praveen5959** [comment]
Hi @danmarshall I upgraded my npm and tried `npm run build`, but this time I am getting different error.
![image](https://user-images.githubusercontent.com/30530587/148521498-a9919cb1-06ba-493d-9353-7f99972e607f.png)

**Comment by danmarshall** [comment]
Did you `npm install` after the upgrade to 7?

**Comment by praveen5959** [comment]
Hi @danmarshall after upgrading the npm version, I did clone the whole repo freshly. So yes, I did do `npm install`.

**Comment by danmarshall** [comment]
Can you tell me which platform you're using? It works on my Windows laptop and on our Linux CI.

Also, do you have any more specific error output?

**Comment by praveen5959** [comment]
Hi @danmarshall I solved that issue. I downgraded node to lower version of v14 and now `npm run build` command is running with no errors.

On the other note I have made some changes to sanddance-explorer package, I want to package that to be consumed in my other React application. How can I package updated sanddance-explorer package and maybe generate .tgz file?

**Comment by danmarshall** [comment]
You can `cd packages/sanddance-explorer` and then run `npm publish` etc. from there.

**Comment by praveen5959** [comment]
Hi @danmarshall that was helpful. 

Closing this issue.
