### ISSUE TITLE
[bug] react version dependencies locked at 16.x

### ISSUE THREAD

**Issue by amcdnl** [microsoft/SandDance#393]
## Issue
When trying to install sanddance-react I get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myproj@0.1.0
npm ERR! Found: @types/react@17.0.38
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^17.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.9.34" from @msrvida/sanddance-react@3.0.1
npm ERR! node_modules/@msrvida/sanddance-react
npm ERR!   @msrvida/sanddance-react@"3.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

My dependencies are set to:

```
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.2",
    "react-dom": "^17.0.2",
    "react": "^17.0.2",
```

I believe the package should loosen these dependencies given that 17.x has no breaking changes for this project.

**Comment by danmarshall** [comment]
Hi @amcdnl , first off, just making sure you have at least npm 7 for the peer dependency part. Yes we ought to be able to support React@17, as long as `@types\react` is compatible.

**Comment by amcdnl** [comment]
```
me@mbp  ~  npm --version
8.1.0
```

**Comment by danmarshall** [comment]
Hi Austin, as we rely on [@fluentui/react](https://github.com/microsoft/fluentui) version 7, we are in lockstep with their peer deps. See https://github.com/microsoft/fluentui/issues/20145

Their version 8 however, specifies compat with React 17. 

Which means to support this at this time, we'd need to major-version-bump our packages:
* @msrvida/sanddance-explorer
* @msrvida/sanddance-embed
Which means supporting current v3 and next v4 of each of these packages.

It may be easier for you to republish under your own org on npm (swap out @msrvida with your org name) if you're open to that.

**Comment by danmarshall** [comment]
My current plan is to major bump all packages in this repo to v4 (in a future major release) and at that time, set React 17 as the minimum.

**Comment by amcdnl** [comment]
@danmarshall - Thanks for the update. Is there a timeframe for that set yet?

**Comment by danmarshall** [comment]
@amcdnl  Nothing in stone, but shooting for mid-year.

**Comment by amcdnl** [comment]
Thanks @danmarshall - 18 will be out by then :D

**Comment by danmarshall** [comment]
Hi @amcdnl , we've got a [beta of our next major version 4](https://microsoft.github.io/SandDance/examples/) which uses react@17. I know that 18 is now out, but [@fluentui/react](https://www.npmjs.com/package/@fluentui/react) is `>=16.8.0 <18.0.0`. When they go to 18 we can do a minor version bump.
