### ISSUE TITLE
Color by dropdown area should have "click to change"

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/SandDance#4]
It's not clear that the color by area is driven by the "Color by" choice. I tried to change by clicking on the paint brush icon (which seems clickable) but this didn't work. That would've been my immediate solution to switching it up.

![image](https://user-images.githubusercontent.com/10819925/56236483-9117b680-603e-11e9-9b59-e0bd7a7fc60f.png)

**Comment by danmarshall** [comment]
This is now available, by clicking on the title. 🙏
