### ISSUE TITLE
[feature] expose aggregated data

### ISSUE THREAD

**Issue by amcdnl** [microsoft/SandDance#401]
## Requirement
It would be ideal if after the chart mounts and processes the data, that it would return the aggregated data. This is useful for if a user wants to build their own legend or show the details of the data in a summary view. 

I'm thinking the interface could look like:

```tsx
<SandDanceReact
   onViewLoaded={({ data })=> {
     console.log('Aggregated Data =>', data');
  }}
/>
```

**Comment by danmarshall** [comment]
Hi Austin, you can access the [Vega View instance](https://vega.github.io/vega/docs/api/view/) via the sanddance [viewer.vegaViewGl](https://microsoft.github.io/SandDance/docs/sanddance/v3/classes/viewer.html#vegaviewgl) property. In the current version of Vega, you can acess the `_runtime.data` property to browse the (root scope) transformations used to produce a chart. Each chart type will have a different set of transforms. You can also look at the Vega spec via [viewer.vegaSpec](https://microsoft.github.io/SandDance/docs/sanddance/v3/classes/viewer.html#vegaspec) to see how the transforms are specified. 

Also note that the Vega spec has "scopes" (which correspond with `_runtime.subcontext` array items) , which are used recursively to layout data for a chart. For example, if you facet the DemoVote data by *state*, and wish to get the aggregation for *Washington* at *latitude 120*, you would need to traverse the subContext's data. 
![image](https://user-images.githubusercontent.com/11507384/150421235-92e3372c-cd8a-4ed5-88db-8604e3d72935.png)

**Comment by amcdnl** [comment]
Thanks @danmarshall - this is very helpful!
