### ISSUE TITLE
Chart Type Stacks not working.

### ISSUE THREAD

**Issue by praveen5959** [microsoft/SandDance#404]
Hi Team,

When I upload the csv with less than 3 rows then chart type Stacks doesn't load in 3D mode, but with rows more than 3 rows is working fine. 

This can be observed even on the demo [site](https://microsoft.github.io/SandDance/app/).

Any reason why this is not working for files less than 3 rows?

**Comment by danmarshall** [comment]
Thanks Praveen for finding this bug. I've tracked it down to a Vega data sequence here:
https://github.com/microsoft/SandDance/blob/master/packages/sanddance-specs/src/layouts/stack.ts#L96

The signal should be `min(sqrt(${names.globalExtent}[1]),2)` so that this data sequence will contain at least one element.

**Comment by praveen5959** [comment]
Hi @danmarshall 

I made that change and ran the `npm run build`. But still I am facing similar issue. I am new to monorepo structure. So am I missing something in the build process?

**Comment by danmarshall** [comment]
Are you also using the `npm start` command?

**Comment by praveen5959** [comment]
No, I am building and packaging the `sanddance-explorer` package. Which I am consuming in another React App that I am working on.

**Comment by danmarshall** [comment]
Your app is probably using the version from npm then, and not pulling the one you’ve modified. This change is in the `sanddance-specs` project, which is a couple levels of dependencies deep from `sanddance-explorer`.

**Comment by praveen5959** [comment]
Yeah, so how to make this change and build `sanddance-explorer` locally?  Also is this solution planned to be fixed in future releases?

**Comment by danmarshall** [comment]
Hi @praveen5959 - I've checked in the fix and published a new version of `@msrvida/sanddance-specs` version `1.4.4`. To pick up this change, you may need to `npm uninstall @msrvida/sanddance-explorer` and then `npm install @msrvida/sanddance-explorer` again to pull in the update.
