### ISSUE TITLE
Tooltip Customization

### ISSUE THREAD

**Issue by amcdnl** [microsoft/SandDance#418]
## Issue
Currently the tooltip is limited to only show key value pairs of the values you are hovering. 

The component exposes a `displayValue` ( https://microsoft.github.io/SandDance/docs/sanddance/v3/interfaces/types.tooltipoptions.html ) option for the tooltip, however, that only gives you the ability to change the display value. 

Furthermore, it does not support React components. If you pass a react component as the display value, it will render `[object Object]`.

It would be ideal, if there was the ability to pass a custom component to the component. For instance:

```jsx
<SandDanceReact
  data={data}
  viewerOptions={{
    tooltipOptions: {
      tooltip: (values) => {
        return <MyFancyTooltip {...values} />;
      }
    }
  }
/>
```

I realize the React component is only an abstraction over the vega and deck libraries which are not react specific either so this would need a little bit of magic to make it work.

**Comment by danmarshall** [comment]
You are correct, that the lower-level non-React libraries might not accept this. Perhaps the callback can just pass mouse the mouse event, so that you might cancel the event (to prevent default rendering) and use the mouse coordinates to place your own component?

**Comment by amcdnl** [comment]
>  Perhaps the callback can just pass mouse the mouse event, so that you might cancel the event (to prevent default rendering) and use the mouse coordinates to place your own component?

Ya - that might work. Here is how I would imagine that interface might look w/ the approach you suggested:

```
<SandDanceReact
  data={data}
  viewerOptions={{
    tooltipOptions: {
      onTooltipEnter: (event: MouseEvent, values: any) => {
        // Do something like this to prevent current tooltip
        // event.preventDefault();
      },
      onTooltipLeave: (event: MouseEvent) => {
        // Need this to know when to kill the tooltip
      }
    }
  }
/>
```

then I could use a portal to add the tooltip to the body and position it via popper or something.

**Comment by amcdnl** [comment]
@danmarshall - Wanted to check if you had an opinion on the API - i might be able to help pick this up if you can point me in the right direction.

**Comment by danmarshall** [comment]
Thanks so much for the offer, Austin! Perhaps you can rename to 

```js
      onTooltipCreate?: (event: MouseEvent, dataRow: object) => {
        // Do something like this to prevent current tooltip
      },
      onTooltipFinalize?: () => {
        // Need this to know when to kill the tooltip
      }
```
Also, we'll need to account for the `exclude` part of [TooltipOptions](https://github.com/microsoft/SandDance/blob/aa2bb89da302dcb7cdc1a1c88b98936ad0c553af/packages/sanddance/src/types.ts#L372) so that a user can choose to hide some of the fields.

**Comment by amcdnl** [comment]
> Perhaps you can rename to...

Personally `onTooltipFinalize` sounds like it means the tooltip loaded vs unmounting.

> we'll need to account for the exclude part 

Wouldn't `exclude` be irrelevant in this case since the user is handling the tooltip themselves? I would imagine if you had these hooked up it would be fully on the user to determine the tooltip visibility/content/etc.

**Comment by danmarshall** [comment]
There already is a user-facing feature to exclude columns, which is why it would need to be honored:

![21CED143-41AA-4CFA-811F-B69FA1160043](https://user-images.githubusercontent.com/11507384/160291278-5dffc39e-a092-40d3-b24a-015c9557d318.jpeg)

![069D4D5F-5EF6-4884-A555-251905198489](https://user-images.githubusercontent.com/11507384/160291289-512b7615-9866-4de1-93d9-d3dd15f7d86f.jpeg)

**Comment by danmarshall** [comment]
We could go with create/destroy for naming.

**Comment by danmarshall** [comment]
Hi @amcdnl , take a look at the API change in PR #493. This will allow you to provide your own tooltips. 

```ts
export interface TooltipCreateOptions {
    dataItem: object;
    event: MouseEvent | PointerEvent | TouchEvent;
}

export interface TooltipDestroyable {
    destroy: () => void;
}

export interface TooltipOptions {
    prepareDataItem?: (dataItem: object) => object;
    create?: (props: TooltipCreateOptions) => TooltipDestroyable;
}
```

If you have any feedback, we can still modify this interface while we are still in a beta phase for v4.
