### ISSUE TITLE
Strings with only numeric characters automatically converted to integer

### ISSUE THREAD

**Issue by DBHey** [microsoft/SandDance#421]
If a column (datatype nvarchar()) has only numeric values, SandDance automatically converts this to an integer. This is problematic if this column is a label with distinct values, however it gets displayed and grouped with the values in a range (ie - 5, 10, 15 instead of 0001, 0003, 0006, 0012 etc...)

I would suggest that if a column value has leading 0's, the assumption should be that it is in fact a string. If it were an integer, it would not have a leading zero. There are many cases where you could have a numeric code that is legitimately a string and striping the leading zeros causes a loss of data and loss of sorting ability.

**Comment by danmarshall** [comment]
Related: #270
