### ISSUE TITLE
Page error if chart type is stacks

### ISSUE THREAD

**Issue by Wigithub1201** [microsoft/SandDance#440]
![image](https://user-images.githubusercontent.com/27763586/167567644-a1f93c78-ae51-4ba8-86ae-38d4926caded.png)
Hi ! I wonder why when I switch chart type to stacks, the chart does not show, the page has an error, as shown in the picture above.
The installation package is installed through npm.  version is as follows.

 "@deck.gl/core": "^8.7.8",
  "@deck.gl/layers": "^8.7.8",
  "@fluentui/react": "^8.67.2",
  "@luma.gl/core": "^8.5.10",
  "@msrvida/sanddance": "^3.2.1",
  "@msrvida/sanddance-explorer": "^3.2.0",
  "vega": "^5.22.1",
   "react": "^16.12.0",

**Comment by danmarshall** [comment]
Can you provide the data sample, or other way to repro?

**Comment by Wigithub1201** [comment]
> Can you provide the data sample, or other way to repro?



> Can you provide the data sample, or other way to repro?

**Comment by Wigithub1201** [comment]
> Can you provide the data sample, or other way to repro?

Hi, I used data from sanddance's website, downloaded from this address 'https://microsoft.github.io/SandDance/app/' .
The relevant codes are as follows.

```
import React, { useEffect, useState } from 'react';
import * as deck from '@deck.gl/core';
import * as layers from '@deck.gl/layers';
import * as luma from '@luma.gl/core';
import * as vega from 'vega';
import * as ReactDOM from 'react-dom';
import { Explorer, use } from '@msrvida/sanddance-explorer';
import * as fluentui from '@fluentui/react';
import './sanddance-app.css';
import './sanddance-app-site.css';
import './sanddance-explorer.css';

const Visualization = (props) => {
    let fileSrc = '/download/data?f=demo.csv';

    const [tableData, setTableData] = useState([]);

    const handleData = (dataFile) => {
        let loader = vega.loader();

        function handleRawText(text) {
            let data = vega.read(text, {
                type: dataFile.type,
                parse: 'auto'
            });
            setTableData(data);
        }
        loader.load(dataFile.dataUrl).then(handleRawText);
    }

    useEffect(() => {
        handleData({ dataUrl: fileSrc, type: 'csv' })
    }, []);

    useEffect(() => {
        if (tableData.length > 0) {
            const explorerProps = {
                logoClickUrl: 'javascript:;',
                logoClickTarget: '_self',
                mounted: explorer => {
                    explorer.load(tableData); // 这里传进去的数据格式和官网是一样的
                }
            };
            fluentui.initializeIcons();
            use(fluentui, React, ReactDOM, vega, deck, layers, luma);
            ReactDOM.render(React.createElement(Explorer, explorerProps), document.getElementById('app'));
        }
    }, [tableData])

    return (
        <>
            <div id="app"></div>
        </>
    )
}

export default Visualization;
```

**Comment by danmarshall** [comment]
Can you also provide the column mappings you used? For example:
![image](https://user-images.githubusercontent.com/11507384/167753107-3850f3fc-413d-478d-897f-1a0c03be5bf1.png)

**Comment by Wigithub1201** [comment]
![1652236082(1)](https://user-images.githubusercontent.com/27763586/167756723-4eca5a8a-4edc-4a63-8a68-3aca825c6e31.png)
Hi, I wonder if it is related to this problem. When entering the page after initialization, the effect of chart type on the left is not selected, but the chart on the right is displayed. Do you know how to fix this problem.

**Comment by danmarshall** [comment]
Can you create a git repo so that I can install the entire project?

**Comment by Wigithub1201** [comment]
> Can you create a git repo so that I can install the entire project?

https://github.com/Wigithub1201/sanddance-wi.git

**Comment by danmarshall** [comment]
Thanks for the repo. You are correct that some of these issues are version related. We currently refer to `@fluentui/react ^7.150.0` which in turn only uses `react@16`.

I have noticed the bug is not with the Stacks layout, but when trying to render a 3D chart. (click the 3D cube icon in the top bar to see the error with any layout.)

When I pin the deck.gl versions to `8.3.7`, it seems to work. See my fork: https://github.com/danmarshall/sanddance-wi

https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/README.md#installation

Sorry for the inconvenience. We will be upgrading react & fluentui in our next major version coming soon.

**Comment by Wigithub1201** [comment]
> Thanks for the repo. You are correct that some of these issues are version related. We currently refer to `@fluentui/react ^7.150.0` which in turn only uses `react@16`.
> 
> I have noticed the bug is not with the Stacks layout, but when trying to render a 3D chart. (click the 3D cube icon in the top bar to see the error with any layout.)
> 
> When I pin the deck.gl versions to `8.3.7`, it seems to work. See my fork: https://github.com/danmarshall/sanddance-wi
> 
> https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/README.md#installation
> 
> Sorry for the inconvenience. We will be upgrading react & fluentui in our next major version coming soon.

ok！Thank you for your help!
