### ISSUE TITLE
Axis does not presents correctly in vscode extension SandDance 

### ISSUE THREAD

**Issue by JOJuYeon** [microsoft/SandDance#445]

**Comment by danmarshall** [comment]
At first glance, it appears that these values are being sorted as strings. Can you ensure there are only numeric values in this column? It only takes one NaN to force the entire column to a string.

**Comment by JOJuYeon** [comment]
Thank you so much, I was mixing string and values. I am very happy with sanddance.

**Comment by JOJuYeon** [comment]
Thank you so much, I was mixing string and values. I am very happy with sanddance.
