### ISSUE TITLE
v4 release date?

### ISSUE THREAD

**Issue by amcdnl** [microsoft/SandDance#510]
I was wondering when the v4 release was scheduled? I noticed all the version bumps in the packages but didn't see it published on npm.

**Comment by danmarshall** [comment]
Our "fuzzy" date is: Summer 2022. 
We're asking the community to please test drive our beta from the links here: https://microsoft.github.io/SandDance/examples/
and report any issues.

**Comment by amcdnl** [comment]
Can you release this to npm as a beta so we can try it?

**Comment by danmarshall** [comment]
Yes, it's already been published to npm with beta versions:
https://www.npmjs.com/package/@msrvida/sanddance
https://www.npmjs.com/package/@msrvida/sanddance-explorer

**Comment by amcdnl** [comment]
What about the react version?

**Comment by danmarshall** [comment]
Yes it's also there:
https://www.npmjs.com/package/@msrvida/sanddance-react
