### ISSUE TITLE
Installation without node

### ISSUE THREAD

**Issue by quamis** [microsoft/SandDance#543]
Can I integrate SandDance in a PHP-based project? I cannot find docs on how to actually integrate this project in another project.

This obviously is not a bug, but the discussions list in github seems to be abandoned.

**Comment by danmarshall** [comment]
Hello, yes you certainly can. Our documentation is not fully built yet 😣 but we've got some examples here:
https://microsoft.github.io/SandDance/examples/

Look for the ones marked UMD/CDN. If you view-page-source you can see how to do it from script tags. These examples are for the SandDance canvas control. If you want the full featured SandDance Explorer, you might try our embeddable iframe version for the easiest integration. Once again, view-page-source of this example: https://microsoft.github.io/SandDance/embed/v4/test.html

**Comment by quamis** [comment]
Thank you, It's what I need. This should probably be mentioned in the main README.
