### ISSUE TITLE
Z-Axis is displaying reversed order

### ISSUE THREAD

**Issue by LarsHilden** [microsoft/SandDance#546]
The Z-axis displays reversed order - Showing 0% where it should be 100% and vice versa.

![image](https://user-images.githubusercontent.com/91375961/197186860-80d32dbf-430c-4883-877e-88c8c9af6289.png)

**Comment by kaddis-clar** [comment]
I'm having the same issue as well. My dashboard was working fine last week, now I'm getting complaints that Z-axis is inverted.

**Comment by danmarshall** [comment]
🤦🏽‍♂️ Thanks for the report! Fix is on the way...
