### ISSUE TITLE
HELP! with 3D column layout - no y axis only x and z - see screenshot

### ISSUE THREAD

**Issue by anywhereanytime** [microsoft/SandDance#547]
![image](https://user-images.githubusercontent.com/14352954/198373855-df791b56-83c1-47e6-b390-fe808bae66bb.png)

**Comment by danmarshall** [comment]
The Column chart puts units into bins on the x axis. The Y axis is then an aggregate of what's in each bin. The default is a count of how many units are in the bin. You can change the aggregate type with the Total By mapping dropdown. The other aggregate operation is a sum.
