### ISSUE TITLE
3D Scatter Chart Decimal Labels for Whole Numbers

### ISSUE THREAD

**Issue by chrisheltzel** [microsoft/SandDance#563]
I am charting whole number values along the X, Y and Z axes.  It look like if there are less than about nine values the labels show spaces for decimal values.  As an example if the data for the X axis contains values of 1, 2, 3, 4 and 5, the labels will be 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5 and 5.  This would be understandable if the data were real numbers, but they are integers.  It would be nice if the chart did not add the extra spaces and labels when whole numbers are defined.

**Comment by danmarshall** [comment]
Thanks for reporting. Can you provide an example dataset?

**Comment by chrisheltzel** [comment]
The attached zip file contains the example.  Note that you can filter the Y Axis to show less than about nine Years and it will also start displaying decimals.
[3D_Scatter_Integers.zip](https://github.com/microsoft/SandDance/files/10314503/3D_Scatter_Integers.zip)

**Comment by danmarshall** [comment]
I've got [a fix for this](https://github.com/microsoft/SandDance/commit/051ad645a28aaaaceb73cc22676fa76deb218ad9) that will need some testing. There is a similar behavior on Column charts, which can be mitigated with the Max Bins slider:
<img width="207" alt="image" src="https://user-images.githubusercontent.com/11507384/210121370-12419c3b-9a19-4083-8325-e65ba5d194f6.png">
However, for Scatter charts, the [scales are quantitative](https://vega.github.io/vega/docs/scales/#quantitative) and aren't binned, so there is no slider.

**Comment by danmarshall** [comment]
Related: #166

**Comment by chrisheltzel** [comment]
Thanks, Dan.  Any idea when this fix will be released?

**Comment by danmarshall** [comment]
Hi @chrisheltzel , this is now live on our [web app](https://microsoft.github.io/SandDance/app/) but it won't make it to PowerBI for another couple weeks.

[This example](https://microsoft.github.io/SandDance/tests/v4/umd/quanBarChartTest.html) shows the fix (x axis bins previously contained ".5" )
