### ISSUE TITLE
For Embed Control, send message to host for onSelect event.

### ISSUE THREAD

**Issue by mscherotter** [microsoft/SandDance#585]
The hosting page should get a message when a user selects a data item to better integrate with the hosting site.

**Comment by danmarshall** [comment]
Implemented as `onCubeClick` and `onCanvasClick` (when clicked away)

**Comment by mscherotter** [comment]
I am getting the eventCubeClicked in the hosting frame but not the canvas clicked.  Please advise.

**Comment by danmarshall** [comment]
Looks like I needed to bump the sanddance-explorer package, can you try again?
