### ISSUE TITLE
Hiding tooltip for a column isn't in insight returned from iframe

### ISSUE THREAD

**Issue by mscherotter** [microsoft/SandDance#592]
Steps to reproduce:
1. load data
2. hide a column for tooltip
3. get insights
There is no insight information on hiding a tooltip column.

How do I specify that a column should be hidden in the tooltip in the insight?

**Comment by danmarshall** [comment]
Can you try adding a [tooltipExclusions](https://microsoft.github.io/SandDance/docs/sanddance-explorer/v4/interfaces/Options.html#tooltipExclusions) string array to an [options object](https://microsoft.github.io/SandDance/docs/sanddance-embed/v4/interfaces/types_message_request.MessageRequest_Load.html#options) passed to your `load` command?

**Comment by mscherotter** [comment]
That works!
