### ISSUE TITLE
Add setup parameter to load message

### ISSUE THREAD

**Issue by mscherotter** [microsoft/SandDance#593]
- In order to fully configure the SandDance embed control, you need to add a setup parameter to the data object sent using the "load" postMessage()
- Document the setup object
- Add another event to return the setup object, similar to the insight event.

**Comment by danmarshall** [comment]
You can now pass an [options](https://microsoft.github.io/SandDance/docs/sanddance-embed/v4/interfaces/types_message_request.MessageRequest_Load.html#options) object to the load command. The options object has a [setup](https://microsoft.github.io/SandDance/docs/sanddance-explorer/v4/interfaces/Options.html#setup) property.

There is now a [getStup](https://microsoft.github.io/SandDance/docs/sanddance-embed/v4/interfaces/types_message_request.MessageRequest_GetSetup.html) request, here is an example in action: https://microsoft.github.io/SandDance/embed/v4/dynamic/test.html
