### ISSUE TITLE
WCAG 4.1.2: Ensures ARIA attributes are allowed for an element's role (button[title="Float toolbar"])

### ISSUE THREAD

**Issue by mscherotter** [microsoft/SandDance#601]
#### Issue
`Ensures ARIA attributes are allowed for an element's role` ([aria-allowed-attr](https://accessibilityinsights.io/info-examples/web/aria-allowed-attr))
#### Target application
[Galeryst Data](https://localhost:8000/data)
#### Element path
#sanddance;button[title="Float toolbar"]
#### Snippet
`<button type="button" role="button" aria-selected="false" class="ms-Button ms-Button--icon vbutton root-139" title="Float toolbar" data-is-focusable="true">`
#### How to fix
    Fix any of the following:
      ARIA attribute is not allowed: aria-selected="false"
#### Environment
Microsoft Edge version 109.0.1518.61
This accessibility issue was found using Accessibility Insights for Web 2.36.1 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

**Comment by danmarshall** [comment]
Fixed in #737
