### ISSUE TITLE
Unable to visualize data

### ISSUE THREAD

**Issue by grizzlybearg** [microsoft/SandDance#616]
![Screenshot 2023-02-18 130024](https://user-images.githubusercontent.com/119950394/219854325-8e63c3dc-7634-4286-bb61-caee307204a4.png)
When starting out, I was able to visualize data from csv files easily. The second time I opened a csv using the extension, no visual graphs could be seen. I've tried reinstalling the extension but nothing changes. The screenshot uploaded shows the output of Treemap charts. The other chart types fail to show as well. How do I fix this?

**Comment by danmarshall** [comment]
Looks like you've hit a bug. Can you try loading this same data into our [web app](https://microsoft.github.io/SandDance/app/), open the JavaScript console and see if there are any errors?

**Comment by grizzlybearg** [comment]
@danmarshall Loading the data with the web app works

**Comment by danmarshall** [comment]
Can you provide a data sample which repros the error?
