### ISSUE TITLE
Using a 16-digit ID for X-Axis is being trimmed or rounded

### ISSUE THREAD

**Issue by JohnnySanabria** [microsoft/SandDance#659]
![image](https://github.com/microsoft/SandDance/assets/107206758/4dcf83cb-d004-4b4d-b1db-f0d8e2798a5f)

As you can see in the image, the ID should look like 3241029088747520, but it is displaying as 3241000000000000 which also leads to it grouping multiple lanes in one bar.

**Comment by danmarshall** [comment]
Can you provide a small data sample?

**Comment by JohnnySanabria** [comment]
Here's some sample data. I would like to see bars labeled by their laneId on the X-Axis and ParcelCopuntInLane on the Y-Axis:

`
ParcelCountInLane	WeightInLane	VolumeInLane	TotalLaneWeightCapacity	LaneId
9	30.00	6880.000000	750.000000	3220311137312768
20	210.00	11224.000000	750.000000	3220311295418368
2	10.00	2000.000000	999.000000	3220312332320768
9	45.00	9000.000000	750.000000	3220900870627328
9	695.00	321832.000000	750.000000	3220979170344960
1	15.00	576.000000	750.000000	3221576891564032
10	32.00	7456.000000	750.000000	3221653418532864
17	85.00	9792.000000	750.000000	3224407942938624
7	14.00	4032.000000	750.000000	3224462583382016
169	338.00	97344.000000	750.000000	3224495904808960`

LaneId is unique across all rows, but it is grouping several rows in same value along the X-axis.
