### ISSUE TITLE
PowerBI Background Image not working

### ISSUE THREAD

**Issue by novnovaa** [microsoft/SandDance#704]
Hi I downloaded the latest PowerBI Sanddance visual version 4.1.2 however the background image setting is not working.
As shown in the snapshot below, I have x and y axis set using numerical data but the "Bottom extent" and "Top extent" setting is not showing, and the "Apply" button is greyed out and remains un-selectable. 
The same is for scatterplots, density and stack plots.
Could someone help resolve this issue?

![image](https://github.com/microsoft/SandDance/assets/171526069/5b0a5566-1090-4599-ab00-80a964b78759)

![image](https://github.com/microsoft/SandDance/assets/171526069/6788b960-5878-4657-94e4-ca0ff4dd5f5b)
![image](https://github.com/microsoft/SandDance/assets/171526069/a4c6e782-ce9e-4d31-85e3-194be86b0a90)

Thank you,

**Comment by danmarshall** [comment]
Hello, the Apply button should be enabled when you have uploaded a file.

**Comment by novnovaa** [comment]
> Hello, the Apply button should be enabled when you have uploaded a file.

Hello, even if the file is uploaded, the apply button doesnt get enabled, also the "Bottom extent" and "Top extent" setting is not showing so the range setting is not possible.

**Comment by danmarshall** [comment]
Can you share a small data sample?

**Comment by novnovaa** [comment]
> Can you share a small data sample?
Sure, here is a dummy data. I tried uploading a random photo for background image but like in below snapshot, it doesnt seem to work...
Appreciate your help, thank you.

[SandDance_PowerBI_BackgroundImageTrial.zip](https://github.com/user-attachments/files/15544038/SandDance_PowerBI_BackgroundImageTrial.zip)

![image](https://github.com/microsoft/SandDance/assets/171526069/9fefc292-b3fb-4e57-94a0-2368a74e4af3)

**Comment by novnovaa** [comment]
> Can you share a small data sample?

hi do you have any idea on a workaround? 
thank you

**Comment by novnovaa** [comment]
> Can you share a small data sample?

hi do you have any idea on a workaround?
thank you

**Comment by danmarshall** [comment]
Hi @novnovaa , I was able to repro this in Power BI Desktop. Please stay tuned for a fix.

**Comment by danmarshall** [comment]
Hello, I've got a fix for this issue. It will take time to get it deployed to Power BI AppSource, so if you want a faster fix, you may want to use this local pbiviz file (which has a different name than the production version so that you can run both side by side).  
[SandDance2019_BGImageFix.1.0.0.0.zip](https://github.com/user-attachments/files/16062628/SandDance2019_BGImageFix.1.0.0.0.zip) .
If you change your existing visual to this new one, then fix the bg image issue, you can then switch back to the real version and it should work as it should. The new one will populate the missing fields.

**Comment by novnovaa** [comment]
> Hello, I've got a fix for this issue. It will take time to get it deployed to Power BI AppSource, so if you want a faster fix, you may want to use this local pbiviz file (which has a different name than the production version so that you can run both side by side). [SandDance2019_BGImageFix.1.0.0.0.zip](https://github.com/user-attachments/files/16062628/SandDance2019_BGImageFix.1.0.0.0.zip) . If you change your existing visual to this new one, then fix the bg image issue, you can then switch back to the real version and it should work as it should. The new one will populate the missing fields.

Thank you for the update, however it seems the same issue is occuring still..
only the first data column added to the values seems to be recognized as the axis and the remaining values wont get recognized as range in the background image setting.

[SandDance_PowerBI_BackgroundImageTrial (2).zip](https://github.com/user-attachments/files/16075725/SandDance_PowerBI_BackgroundImageTrial.2.zip)

![image](https://github.com/microsoft/SandDance/assets/171526069/a353b344-639f-4dc3-9921-1e854fdd2d7f)

**Comment by danmarshall** [comment]
Thanks for verifying, here's an update:
[SandDance2019_BGImageFix2.1.0.0.0.zip](https://github.com/user-attachments/files/16138011/SandDance2019_BGImageFix2.1.0.0.0.zip)

**Comment by novnovaa** [comment]
Thank you so much! its now working

**Comment by novnovaa** [comment]
Thank you so much! its now working
