### ISSUE TITLE
"Try it now on the web" displays blank page

### ISSUE THREAD

**Issue by ChrisRus** [microsoft/SandDance#731]
The online demo application does not appear to render any content.

https://microsoft.github.io/SandDance/app/

^-- using latest version of Edge browser on corporate laptop.

**Comment by hydrosquall** [comment]
Reproduced on Chrome browser on MacOS too - this error appears in the console.

![Image](https://github.com/user-attachments/assets/2b5b554e-b3bf-4657-af59-ece754416638)

**Comment by danmarshall** [comment]
My investigation is still continuing as to the cause of the build breakage, but the PR reverted the outputs so at least the app is up again.
