### ISSUE TITLE
Lacking support for UTF-8?

### ISSUE THREAD

**Issue by XZJIsme** [microsoft/SandDance#78]
It can't display Chinese, Japanese etc

**Comment by danmarshall** [comment]
Thanks for filing this. Looks like a matter of passing a character set to the layer: https://github.com/uber/deck.gl/blob/6.4-release/docs/layers/text-layer.md#characterset-array--string-optional

**Comment by cjd9023** [comment]
@ZJisme   请教下,中文乱码如何解决.,
